test_timeout_crm = '32 min'
cloudlet_name_azure = 'automationAzureCentralCloudlet'
cloudlet_name_openstack = 'automationHamburgCloudlet'
docker_image = 'docker-qa.mobiledgex.net/mobiledgex/images/server_ping_threaded:5.0'
qcow_centos_image = 'https://artifactory-qa.mobiledgex.net/artifactory/mobiledgex/server_ping_threaded_centos7.qcow2#md5:eddafc541f1642b76a1c30062116719d'
qcow_centos_image_notrunning = 'https://artifactory-qa.mobiledgex.net/artifactory/mobiledgex/server_ping_threaded_notrunning_centos7.qcow2#md5:7a08091f71f1e447ce291e467cc3926c'
qcow_centos_openstack_image = 'server_ping_threaded_centos7'
