# Copyright 2022 MobiledgeX, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

description: Create a VM
heat_template_version: '2016-10-14'
resources:
  vmpool-subnet:
    properties:
      cidr: 10.101.253.0/24
      dns_nameservers:
      - 1.1.1.1
      - 1.0.0.1
      enable_dhcp: false
      gateway_ip: ""
      name: mex-automationvmpool-subnet
      network: mex-k8s-net-1
    type: OS::Neutron::Subnet
  vmpoolvm1-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.191
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool1-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port
  vmpoolvm2-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.192
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool2-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port
  vmpoolvm3-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.193
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool3-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port
  vmpoolvm4-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.194
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool4-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port
  vmpoolvm5-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.195
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool5-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port
  vmpoolvm6-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.196
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool6-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port

  vmpoolvm1:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool1
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm1-port }
    type: OS::Nova::Server
  vmpoolvm2:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool2
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm2-port }
    type: OS::Nova::Server
  vmpoolvm3:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool3
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm3-port }
    type: OS::Nova::Server
  vmpoolvm4:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool4
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm4-port }
    type: OS::Nova::Server
  vmpoolvm5:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool5
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm5-port }
    type: OS::Nova::Server
  vmpoolvm6:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool6
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm6-port }
    type: OS::Nova::Server
