description: Create a VM
heat_template_version: '2016-10-14'
resources:
  vmpool-subnet:
    properties:
      cidr: 10.101.255.0/24
      dns_nameservers:
      - 1.1.1.1
      - 1.0.0.1
      enable_dhcp: false
      gateway_ip: ""
      name: mex-vmpool-subnet
      network: mex-k8s-net-1
    type: OS::Neutron::Subnet
  vmpoolvm1-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.255.191
        subnet:
          get_resource: vmpool-subnet
      name: mex-vmpoolvm1-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
    type: OS::Neutron::Port
  vmpoolvm2-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.255.192
        subnet:
          get_resource: vmpool-subnet
      name: mex-vmpoolvm2-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
    type: OS::Neutron::Port
  vmpoolvm3-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.255.193
        subnet:
          get_resource: vmpool-subnet
      name: mex-vmpoolvm3-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
    type: OS::Neutron::Port
  vmpoolvm4-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.255.194
        subnet:
          get_resource: vmpool-subnet
      name: mex-vmpoolvm4-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
    type: OS::Neutron::Port
  vmpoolvm5-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.255.195
        subnet:
          get_resource: vmpool-subnet
      name: mex-vmpoolvm5-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
    type: OS::Neutron::Port
  vmpoolvm6-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.255.196
        subnet:
          get_resource: vmpool-subnet
      name: mex-vmpoolvm6-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
    type: OS::Neutron::Port

  vmpoolvm1:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-3.1.4-ubuntussh
      name: vmpoolvm1
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm1-port }
    type: OS::Nova::Server
  vmpoolvm2:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-3.1.4-ubuntussh
      name: vmpoolvm2
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm2-port }
    type: OS::Nova::Server
  vmpoolvm3:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-3.1.4-ubuntussh
      name: vmpoolvm3
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm3-port }
    type: OS::Nova::Server
  vmpoolvm4:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-3.1.4-ubuntussh
      name: vmpoolvm4
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm4-port }
    type: OS::Nova::Server
  vmpoolvm5:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-3.1.4-ubuntussh
      name: vmpoolvm5
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm5-port }
    type: OS::Nova::Server
  vmpoolvm6:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-3.1.4-ubuntussh
      name: vmpoolvm6
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm6-port }
    type: OS::Nova::Server
