description: Create a VM
heat_template_version: '2016-10-14'
resources:
#  vmpool-securitygroup:
#    type: OS::Neutron::SecurityGroup
#    properties:
#      description: app security group
#      name: appsecuritygroup
#      rules: 
#        - direction: ingress
#          ethertype: IPv4
#          port_range_max: 2015
#          port_range_min: 2015
#          protocol: tcp
#          remote_ip_prefix: 0.0.0.0/0
#        - direction: ingress
#          ethertype: IPv4
#          port_range_max: 2016
#          port_range_min: 2016
#          protocol: tcp
#          remote_ip_prefix: 0.0.0.0/0
#        - direction: ingress
#          ethertype: IPv4
#          port_range_max: 2015
#          port_range_min: 2015
#          protocol: udp
#          remote_ip_prefix: 0.0.0.0/0
#        - direction: ingress
#          ethertype: IPv4
#          port_range_max: 2016
#          port_range_min: 2016
#          protocol: udp
#          remote_ip_prefix: 0.0.0.0/0
#        - direction: ingress
#          ethertype: IPv4
#          port_range_max: 8085 
#          port_range_min: 8085 
#          protocol: tcp
#          remote_ip_prefix: 0.0.0.0/0
#        - direction: ingress
#          ethertype: IPv4
#          port_range_max: 22
#          port_range_min: 22
#          protocol: tcp
#          remote_ip_prefix: 0.0.0.0/0 
#        - direction: ingress
#          ethertype: IPv4
#          port_range_max: 53 
#          port_range_min: 53 
#          protocol: tcp
#          remote_ip_prefix: 0.0.0.0/0 
#        - direction: ingress
#          ethertype: IPv4
#          port_range_max: 443
#          port_range_min: 443
#          protocol: tcp
#          remote_ip_prefix: 0.0.0.0/0
#        - direction: egress
#          ethertype: IPv4

  vmpool-subnet:
    properties:
      cidr: 10.101.253.0/24
      dns_nameservers:
      - 1.1.1.1
      - 1.0.0.1
      enable_dhcp: false
      gateway_ip: ""
      name: mex-automationvmpool-subnet
      network: mex-k8s-net-1
    type: OS::Neutron::Subnet
  vmpoolvm1-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.191
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool1-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port
  vmpoolvm2-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.192
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool2-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port
  vmpoolvm3-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.193
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool3-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port
  vmpoolvm4-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.194
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool4-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port
  vmpoolvm5-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.195
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool5-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port
  vmpoolvm6-port:
    properties:
      fixed_ips:
      - ip_address: 10.101.253.196
        subnet:
          get_resource: vmpool-subnet
      name: mex-automationvmpool6-port
      network_id: mex-k8s-net-1
      port_security_enabled: true
#      security_groups:
#      - { get_resource: vmpool-securitygroup }
    type: OS::Neutron::Port

  vmpoolvm1:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool1
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm1-port }
    type: OS::Nova::Server
  vmpoolvm2:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool2
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm2-port }
    type: OS::Nova::Server
  vmpoolvm3:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool3
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm3-port }
    type: OS::Nova::Server
  vmpoolvm4:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool4
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm4-port }
    type: OS::Nova::Server
  vmpoolvm5:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool5
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm5-port }
    type: OS::Nova::Server
  vmpoolvm6:
    properties:
      config_drive: true
      flavor: m4.medium
      image: mobiledgex-v3.1.6
      name: automationvmpool6
      networks:
      - network: external-network-shared
      - port: { get_resource: vmpoolvm6-port }
    type: OS::Nova::Server
