# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alert.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2
import protogen_pb2 as protogen__pb2
import loc_pb2 as loc__pb2
import gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='alert.proto',
  package='edgeproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x61lert.proto\x12\tedgeproto\x1a\x11\x61nnotations.proto\x1a\x0eprotogen.proto\x1a\tloc.proto\x1a\ngogo.proto\"\x97\x03\n\x05\x41lert\x12,\n\x06labels\x18\x01 \x03(\x0b\x32\x1c.edgeproto.Alert.LabelsEntry\x12\x36\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32!.edgeproto.Alert.AnnotationsEntry\x12\r\n\x05state\x18\x03 \x01(\t\x12<\n\tactive_at\x18\x04 \x01(\x0b\x32#.distributed_match_engine.TimestampB\x04\xc8\xde\x1f\x00\x12\r\n\x05value\x18\x05 \x01(\x01\x12 \n\tnotify_id\x18\x06 \x01(\x03\x42\r\xa8\xf4\x18\x01\x92\xb2\x19\x05nocmp\x12!\n\ncontroller\x18\x07 \x01(\tB\r\xa8\xf4\x18\x01\x92\xb2\x19\x05nocmp\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01:$\xe8\xf3\x18\x01\xf0\xf3\x18\x01\x80\xf4\x18\x01\xa0\xf4\x18\x01\x90\xf4\x18\x01\xe0\xf4\x18\x01\xf2\xf5\x18\x08\x41lertKey2v\n\x08\x41lertApi\x12j\n\tShowAlert\x12\x10.edgeproto.Alert\x1a\x10.edgeproto.Alert\"7\x82\xd3\xe4\x93\x02\x10\"\x0b/show/alert:\x01*\xea\xf4\x18\x19ResourceAlert,ActionView,\xd0\xf5\x18\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[annotations__pb2.DESCRIPTOR,protogen__pb2.DESCRIPTOR,loc__pb2.DESCRIPTOR,gogo__pb2.DESCRIPTOR,])




_ALERT_LABELSENTRY = _descriptor.Descriptor(
  name='LabelsEntry',
  full_name='edgeproto.Alert.LabelsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='edgeproto.Alert.LabelsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='edgeproto.Alert.LabelsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=402,
)

_ALERT_ANNOTATIONSENTRY = _descriptor.Descriptor(
  name='AnnotationsEntry',
  full_name='edgeproto.Alert.AnnotationsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='edgeproto.Alert.AnnotationsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='edgeproto.Alert.AnnotationsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=454,
)

_ALERT = _descriptor.Descriptor(
  name='Alert',
  full_name='edgeproto.Alert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='edgeproto.Alert.labels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='annotations', full_name='edgeproto.Alert.annotations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='edgeproto.Alert.state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active_at', full_name='edgeproto.Alert.active_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='edgeproto.Alert.value', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notify_id', full_name='edgeproto.Alert.notify_id', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\250\364\030\001\222\262\031\005nocmp'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controller', full_name='edgeproto.Alert.controller', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\250\364\030\001\222\262\031\005nocmp'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ALERT_LABELSENTRY, _ALERT_ANNOTATIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\360\363\030\001\200\364\030\001\240\364\030\001\220\364\030\001\340\364\030\001\362\365\030\010AlertKey'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=492,
)

_ALERT_LABELSENTRY.containing_type = _ALERT
_ALERT_ANNOTATIONSENTRY.containing_type = _ALERT
_ALERT.fields_by_name['labels'].message_type = _ALERT_LABELSENTRY
_ALERT.fields_by_name['annotations'].message_type = _ALERT_ANNOTATIONSENTRY
_ALERT.fields_by_name['active_at'].message_type = loc__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Alert'] = _ALERT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Alert = _reflection.GeneratedProtocolMessageType('Alert', (_message.Message,), {

  'LabelsEntry' : _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ALERT_LABELSENTRY,
    '__module__' : 'alert_pb2'
    # @@protoc_insertion_point(class_scope:edgeproto.Alert.LabelsEntry)
    })
  ,

  'AnnotationsEntry' : _reflection.GeneratedProtocolMessageType('AnnotationsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ALERT_ANNOTATIONSENTRY,
    '__module__' : 'alert_pb2'
    # @@protoc_insertion_point(class_scope:edgeproto.Alert.AnnotationsEntry)
    })
  ,
  'DESCRIPTOR' : _ALERT,
  '__module__' : 'alert_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.Alert)
  })
_sym_db.RegisterMessage(Alert)
_sym_db.RegisterMessage(Alert.LabelsEntry)
_sym_db.RegisterMessage(Alert.AnnotationsEntry)


_ALERT_LABELSENTRY._options = None
_ALERT_ANNOTATIONSENTRY._options = None
_ALERT.fields_by_name['active_at']._options = None
_ALERT.fields_by_name['notify_id']._options = None
_ALERT.fields_by_name['controller']._options = None
_ALERT._options = None

_ALERTAPI = _descriptor.ServiceDescriptor(
  name='AlertApi',
  full_name='edgeproto.AlertApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=494,
  serialized_end=612,
  methods=[
  _descriptor.MethodDescriptor(
    name='ShowAlert',
    full_name='edgeproto.AlertApi.ShowAlert',
    index=0,
    containing_service=None,
    input_type=_ALERT,
    output_type=_ALERT,
    serialized_options=_b('\202\323\344\223\002\020\"\013/show/alert:\001*\352\364\030\031ResourceAlert,ActionView,\320\365\030\001'),
  ),
])
_sym_db.RegisterServiceDescriptor(_ALERTAPI)

DESCRIPTOR.services_by_name['AlertApi'] = _ALERTAPI

# @@protoc_insertion_point(module_scope)
