# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app_client_pb2 as app__client__pb2


class MatchEngineApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterClient = channel.unary_unary(
        '/distributed_match_engine.MatchEngineApi/RegisterClient',
        request_serializer=app__client__pb2.RegisterClientRequest.SerializeToString,
        response_deserializer=app__client__pb2.RegisterClientReply.FromString,
        )
    self.FindCloudlet = channel.unary_unary(
        '/distributed_match_engine.MatchEngineApi/FindCloudlet',
        request_serializer=app__client__pb2.FindCloudletRequest.SerializeToString,
        response_deserializer=app__client__pb2.FindCloudletReply.FromString,
        )
    self.VerifyLocation = channel.unary_unary(
        '/distributed_match_engine.MatchEngineApi/VerifyLocation',
        request_serializer=app__client__pb2.VerifyLocationRequest.SerializeToString,
        response_deserializer=app__client__pb2.VerifyLocationReply.FromString,
        )
    self.GetLocation = channel.unary_unary(
        '/distributed_match_engine.MatchEngineApi/GetLocation',
        request_serializer=app__client__pb2.GetLocationRequest.SerializeToString,
        response_deserializer=app__client__pb2.GetLocationReply.FromString,
        )
    self.AddUserToGroup = channel.unary_unary(
        '/distributed_match_engine.MatchEngineApi/AddUserToGroup',
        request_serializer=app__client__pb2.DynamicLocGroupRequest.SerializeToString,
        response_deserializer=app__client__pb2.DynamicLocGroupReply.FromString,
        )
    self.GetAppInstList = channel.unary_unary(
        '/distributed_match_engine.MatchEngineApi/GetAppInstList',
        request_serializer=app__client__pb2.AppInstListRequest.SerializeToString,
        response_deserializer=app__client__pb2.AppInstListReply.FromString,
        )
    self.GetFqdnList = channel.unary_unary(
        '/distributed_match_engine.MatchEngineApi/GetFqdnList',
        request_serializer=app__client__pb2.FqdnListRequest.SerializeToString,
        response_deserializer=app__client__pb2.FqdnListReply.FromString,
        )
    self.GetQosPositionKpi = channel.unary_stream(
        '/distributed_match_engine.MatchEngineApi/GetQosPositionKpi',
        request_serializer=app__client__pb2.QosPositionRequest.SerializeToString,
        response_deserializer=app__client__pb2.QosPositionKpiReply.FromString,
        )


class MatchEngineApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RegisterClient(self, request, context):
    """
    RegisterClient

    Registers the client with the closest Distributed Matching Engine (the
    nearest edge location in the Operator network) and validates the
    legitimacy of the mobile subscriber. All session information is encrypted.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindCloudlet(self, request, context):
    """
    FindCloudlet

    Locates the most optimal edge computing footprint and allows the
    registered application to find the application backend by leveraging the
    location, application subscription, and service provider agreement. If
    there are no suitable cloudlet instances available, the client may connect
    to the application server located in the public cloud.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VerifyLocation(self, request, context):
    """
    VerifyLocation

    Verifies that the GPS coordinates accurately report the actual location of the device.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLocation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddUserToGroup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAppInstList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFqdnList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetQosPositionKpi(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MatchEngineApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterClient': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterClient,
          request_deserializer=app__client__pb2.RegisterClientRequest.FromString,
          response_serializer=app__client__pb2.RegisterClientReply.SerializeToString,
      ),
      'FindCloudlet': grpc.unary_unary_rpc_method_handler(
          servicer.FindCloudlet,
          request_deserializer=app__client__pb2.FindCloudletRequest.FromString,
          response_serializer=app__client__pb2.FindCloudletReply.SerializeToString,
      ),
      'VerifyLocation': grpc.unary_unary_rpc_method_handler(
          servicer.VerifyLocation,
          request_deserializer=app__client__pb2.VerifyLocationRequest.FromString,
          response_serializer=app__client__pb2.VerifyLocationReply.SerializeToString,
      ),
      'GetLocation': grpc.unary_unary_rpc_method_handler(
          servicer.GetLocation,
          request_deserializer=app__client__pb2.GetLocationRequest.FromString,
          response_serializer=app__client__pb2.GetLocationReply.SerializeToString,
      ),
      'AddUserToGroup': grpc.unary_unary_rpc_method_handler(
          servicer.AddUserToGroup,
          request_deserializer=app__client__pb2.DynamicLocGroupRequest.FromString,
          response_serializer=app__client__pb2.DynamicLocGroupReply.SerializeToString,
      ),
      'GetAppInstList': grpc.unary_unary_rpc_method_handler(
          servicer.GetAppInstList,
          request_deserializer=app__client__pb2.AppInstListRequest.FromString,
          response_serializer=app__client__pb2.AppInstListReply.SerializeToString,
      ),
      'GetFqdnList': grpc.unary_unary_rpc_method_handler(
          servicer.GetFqdnList,
          request_deserializer=app__client__pb2.FqdnListRequest.FromString,
          response_serializer=app__client__pb2.FqdnListReply.SerializeToString,
      ),
      'GetQosPositionKpi': grpc.unary_stream_rpc_method_handler(
          servicer.GetQosPositionKpi,
          request_deserializer=app__client__pb2.QosPositionRequest.FromString,
          response_serializer=app__client__pb2.QosPositionKpiReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'distributed_match_engine.MatchEngineApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
