# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appinstclient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2
import protogen_pb2 as protogen__pb2
import loc_pb2 as loc__pb2
import appinst_pb2 as appinst__pb2
import gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='appinstclient.proto',
  package='edgeproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x61ppinstclient.proto\x12\tedgeproto\x1a\x11\x61nnotations.proto\x1a\x0eprotogen.proto\x1a\tloc.proto\x1a\rappinst.proto\x1a\ngogo.proto\"\xfe\x02\n\x10\x41ppInstClientKey\x12(\n\x03key\x18\x01 \x01(\x0b\x32\x15.edgeproto.AppInstKeyB\x04\xc8\xde\x1f\x00\x12\x0c\n\x04uuid\x18\x02 \x01(\t:\xb1\x02\xc0\xf4\x18\x01\xe8\xf3\x18\x01\xf0\xf3\x18\x01\x80\xf4\x18\x01\x90\xf4\x18\x01\x9a\xf5\x18\x98\x02\x61ppname=Key.AppKey.Name,appvers=Key.AppKey.Version,developer=Key.AppKey.DeveloperKey.Name,cluster=Key.ClusterInstKey.ClusterKey.Name,clusterdeveloper=Key.ClusterInstKey.Developer,cloudlet=Key.ClusterInstKey.CloudletKey.Name,operator=Key.ClusterInstKey.CloudletKey.OperatorKey.Name\"\xb9\x01\n\rAppInstClient\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\x12\x35\n\nclient_key\x18\x02 \x01(\x0b\x32\x1b.edgeproto.AppInstClientKeyB\x04\xc8\xde\x1f\x00\x12\x35\n\x08location\x18\x03 \x01(\x0b\x32\x1d.distributed_match_engine.LocB\x04\xc8\xde\x1f\x00\x12 \n\tnotify_id\x18\x04 \x01(\x03\x42\r\xa8\xf4\x18\x01\x92\xb2\x19\x05nocmp:\x08\xc0\xf4\x18\x01\xf0\xf4\x18\x00\x32\xc9\x01\n\x10\x41ppInstClientApi\x12\xb4\x01\n\x11ShowAppInstClient\x12\x1b.edgeproto.AppInstClientKey\x1a\x18.edgeproto.AppInstClient\"f\x82\xd3\xe4\x93\x02\x18\"\x13/show/appinstclient:\x01*\xa8\xf5\x18\x01\xea\xf4\x18<ResourceAppAnalytics,ActionView,Key.AppKey.DeveloperKey.Name\x80\xf6\x18\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[annotations__pb2.DESCRIPTOR,protogen__pb2.DESCRIPTOR,loc__pb2.DESCRIPTOR,appinst__pb2.DESCRIPTOR,gogo__pb2.DESCRIPTOR,])




_APPINSTCLIENTKEY = _descriptor.Descriptor(
  name='AppInstClientKey',
  full_name='edgeproto.AppInstClientKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='edgeproto.AppInstClientKey.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='edgeproto.AppInstClientKey.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\300\364\030\001\350\363\030\001\360\363\030\001\200\364\030\001\220\364\030\001\232\365\030\230\002appname=Key.AppKey.Name,appvers=Key.AppKey.Version,developer=Key.AppKey.DeveloperKey.Name,cluster=Key.ClusterInstKey.ClusterKey.Name,clusterdeveloper=Key.ClusterInstKey.Developer,cloudlet=Key.ClusterInstKey.CloudletKey.Name,operator=Key.ClusterInstKey.CloudletKey.OperatorKey.Name'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=490,
)


_APPINSTCLIENT = _descriptor.Descriptor(
  name='AppInstClient',
  full_name='edgeproto.AppInstClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='edgeproto.AppInstClient.fields', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_key', full_name='edgeproto.AppInstClient.client_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='edgeproto.AppInstClient.location', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notify_id', full_name='edgeproto.AppInstClient.notify_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\250\364\030\001\222\262\031\005nocmp'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\300\364\030\001\360\364\030\000'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=678,
)

_APPINSTCLIENTKEY.fields_by_name['key'].message_type = appinst__pb2._APPINSTKEY
_APPINSTCLIENT.fields_by_name['client_key'].message_type = _APPINSTCLIENTKEY
_APPINSTCLIENT.fields_by_name['location'].message_type = loc__pb2._LOC
DESCRIPTOR.message_types_by_name['AppInstClientKey'] = _APPINSTCLIENTKEY
DESCRIPTOR.message_types_by_name['AppInstClient'] = _APPINSTCLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppInstClientKey = _reflection.GeneratedProtocolMessageType('AppInstClientKey', (_message.Message,), {
  'DESCRIPTOR' : _APPINSTCLIENTKEY,
  '__module__' : 'appinstclient_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.AppInstClientKey)
  })
_sym_db.RegisterMessage(AppInstClientKey)

AppInstClient = _reflection.GeneratedProtocolMessageType('AppInstClient', (_message.Message,), {
  'DESCRIPTOR' : _APPINSTCLIENT,
  '__module__' : 'appinstclient_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.AppInstClient)
  })
_sym_db.RegisterMessage(AppInstClient)


_APPINSTCLIENTKEY.fields_by_name['key']._options = None
_APPINSTCLIENTKEY._options = None
_APPINSTCLIENT.fields_by_name['client_key']._options = None
_APPINSTCLIENT.fields_by_name['location']._options = None
_APPINSTCLIENT.fields_by_name['notify_id']._options = None
_APPINSTCLIENT._options = None

_APPINSTCLIENTAPI = _descriptor.ServiceDescriptor(
  name='AppInstClientApi',
  full_name='edgeproto.AppInstClientApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=681,
  serialized_end=882,
  methods=[
  _descriptor.MethodDescriptor(
    name='ShowAppInstClient',
    full_name='edgeproto.AppInstClientApi.ShowAppInstClient',
    index=0,
    containing_service=None,
    input_type=_APPINSTCLIENTKEY,
    output_type=_APPINSTCLIENT,
    serialized_options=_b('\202\323\344\223\002\030\"\023/show/appinstclient:\001*\250\365\030\001\352\364\030<ResourceAppAnalytics,ActionView,Key.AppKey.DeveloperKey.Name\200\366\030\001'),
  ),
])
_sym_db.RegisterServiceDescriptor(_APPINSTCLIENTAPI)

DESCRIPTOR.services_by_name['AppInstClientApi'] = _APPINSTCLIENTAPI

# @@protoc_insertion_point(module_scope)
