# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import appinst_pb2 as appinst__pb2
import result_pb2 as result__pb2


class AppInstApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateAppInst = channel.unary_stream(
        '/edgeproto.AppInstApi/CreateAppInst',
        request_serializer=appinst__pb2.AppInst.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.DeleteAppInst = channel.unary_stream(
        '/edgeproto.AppInstApi/DeleteAppInst',
        request_serializer=appinst__pb2.AppInst.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.RefreshAppInst = channel.unary_stream(
        '/edgeproto.AppInstApi/RefreshAppInst',
        request_serializer=appinst__pb2.AppInst.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.UpdateAppInst = channel.unary_stream(
        '/edgeproto.AppInstApi/UpdateAppInst',
        request_serializer=appinst__pb2.AppInst.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ShowAppInst = channel.unary_stream(
        '/edgeproto.AppInstApi/ShowAppInst',
        request_serializer=appinst__pb2.AppInst.SerializeToString,
        response_deserializer=appinst__pb2.AppInst.FromString,
        )


class AppInstApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateAppInst(self, request, context):
    """Create Application Instance. Creates an instance of an App on a Cloudlet where it is
    defined by an App plus a ClusterInst key. Many of the fields here are inherited from
    the App definition.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAppInst(self, request, context):
    """Delete Application Instance. Deletes an instance of the App from the Cloudlet.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RefreshAppInst(self, request, context):
    """Refresh Application Instance. Restarts an App instance with new App settings or image.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAppInst(self, request, context):
    """Update Application Instance. Updates an Application instance and then refreshes it.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowAppInst(self, request, context):
    """Show Application Instances. Lists all the Application instances managed by the Edge Controller.
    Any fields specified will be used to filter results.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AppInstApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateAppInst': grpc.unary_stream_rpc_method_handler(
          servicer.CreateAppInst,
          request_deserializer=appinst__pb2.AppInst.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'DeleteAppInst': grpc.unary_stream_rpc_method_handler(
          servicer.DeleteAppInst,
          request_deserializer=appinst__pb2.AppInst.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'RefreshAppInst': grpc.unary_stream_rpc_method_handler(
          servicer.RefreshAppInst,
          request_deserializer=appinst__pb2.AppInst.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'UpdateAppInst': grpc.unary_stream_rpc_method_handler(
          servicer.UpdateAppInst,
          request_deserializer=appinst__pb2.AppInst.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ShowAppInst': grpc.unary_stream_rpc_method_handler(
          servicer.ShowAppInst,
          request_deserializer=appinst__pb2.AppInst.FromString,
          response_serializer=appinst__pb2.AppInst.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.AppInstApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AppInstInfoApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ShowAppInstInfo = channel.unary_stream(
        '/edgeproto.AppInstInfoApi/ShowAppInstInfo',
        request_serializer=appinst__pb2.AppInstInfo.SerializeToString,
        response_deserializer=appinst__pb2.AppInstInfo.FromString,
        )


class AppInstInfoApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ShowAppInstInfo(self, request, context):
    """Show application instances state.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AppInstInfoApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ShowAppInstInfo': grpc.unary_stream_rpc_method_handler(
          servicer.ShowAppInstInfo,
          request_deserializer=appinst__pb2.AppInstInfo.FromString,
          response_serializer=appinst__pb2.AppInstInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.AppInstInfoApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AppInstMetricsApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ShowAppInstMetrics = channel.unary_stream(
        '/edgeproto.AppInstMetricsApi/ShowAppInstMetrics',
        request_serializer=appinst__pb2.AppInstMetrics.SerializeToString,
        response_deserializer=appinst__pb2.AppInstMetrics.FromString,
        )


class AppInstMetricsApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ShowAppInstMetrics(self, request, context):
    """Show application instance metrics.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AppInstMetricsApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ShowAppInstMetrics': grpc.unary_stream_rpc_method_handler(
          servicer.ShowAppInstMetrics,
          request_deserializer=appinst__pb2.AppInstMetrics.FromString,
          response_serializer=appinst__pb2.AppInstMetrics.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.AppInstMetricsApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
