# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import appinstclient_pb2 as appinstclient__pb2


class AppInstClientApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ShowAppInstClient = channel.unary_stream(
        '/edgeproto.AppInstClientApi/ShowAppInstClient',
        request_serializer=appinstclient__pb2.AppInstClientKey.SerializeToString,
        response_deserializer=appinstclient__pb2.AppInstClient.FromString,
        )


class AppInstClientApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ShowAppInstClient(self, request, context):
    """Show application instance clients.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AppInstClientApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ShowAppInstClient': grpc.unary_stream_rpc_method_handler(
          servicer.ShowAppInstClient,
          request_deserializer=appinstclient__pb2.AppInstClientKey.FromString,
          response_serializer=appinstclient__pb2.AppInstClient.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.AppInstClientApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
