# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autoscalepolicy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2
import result_pb2 as result__pb2
import protogen_pb2 as protogen__pb2
import gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='autoscalepolicy.proto',
  package='edgeproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x61utoscalepolicy.proto\x12\tedgeproto\x1a\x11\x61nnotations.proto\x1a\x0cresult.proto\x1a\x0eprotogen.proto\x1a\ngogo.proto\":\n\tPolicyKey\x12\x11\n\tdeveloper\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t:\x0c\xe8\xf3\x18\x01\xf8\xf3\x18\x01\xb0\xa0\x1f\x01\"\x8b\x02\n\x0f\x41utoScalePolicy\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\x12\'\n\x03key\x18\x02 \x01(\x0b\x32\x14.edgeproto.PolicyKeyB\x04\xc8\xde\x1f\x00\x12\x11\n\tmin_nodes\x18\x03 \x01(\r\x12\x11\n\tmax_nodes\x18\x04 \x01(\r\x12\x1b\n\x13scale_up_cpu_thresh\x18\x05 \x01(\r\x12\x1d\n\x15scale_down_cpu_thresh\x18\x06 \x01(\r\x12\x1e\n\x10trigger_time_sec\x18\x07 \x01(\rB\x04\x88\xf4\x18\x01:=\xe8\xf3\x18\x01\xf0\xf3\x18\x01\x98\xf4\x18\x01\x80\xf4\x18\x01\x90\xf4\x18\x01\x9a\xf5\x18%name=Key.Name,developer=Key.Developer2\xba\x05\n\x12\x41utoScalePolicyApi\x12\xb5\x01\n\x15\x43reateAutoScalePolicy\x12\x1a.edgeproto.AutoScalePolicy\x1a\x11.edgeproto.Result\"m\x82\xd3\xe4\x93\x02\x1c\"\x17/create/autoscalepolicy:\x01*\xea\xf4\x18\x32ResourceDeveloperPolicy,ActionManage,Key.Developer\xe2\xf5\x18\x11MinNodes,MaxNodes\x12\xa0\x01\n\x15\x44\x65leteAutoScalePolicy\x12\x1a.edgeproto.AutoScalePolicy\x1a\x11.edgeproto.Result\"X\x82\xd3\xe4\x93\x02\x1c\"\x17/delete/autoscalepolicy:\x01*\xea\xf4\x18\x32ResourceDeveloperPolicy,ActionManage,Key.Developer\x12\xa0\x01\n\x15UpdateAutoScalePolicy\x12\x1a.edgeproto.AutoScalePolicy\x1a\x11.edgeproto.Result\"X\x82\xd3\xe4\x93\x02\x1c\"\x17/update/autoscalepolicy:\x01*\xea\xf4\x18\x32ResourceDeveloperPolicy,ActionManage,Key.Developer\x12\xa5\x01\n\x13ShowAutoScalePolicy\x12\x1a.edgeproto.AutoScalePolicy\x1a\x1a.edgeproto.AutoScalePolicy\"T\x82\xd3\xe4\x93\x02\x1a\"\x15/show/autoscalepolicy:\x01*\xea\xf4\x18\x30ResourceDeveloperPolicy,ActionView,Key.Developer0\x01\x62\x06proto3')
  ,
  dependencies=[annotations__pb2.DESCRIPTOR,result__pb2.DESCRIPTOR,protogen__pb2.DESCRIPTOR,gogo__pb2.DESCRIPTOR,])




_POLICYKEY = _descriptor.Descriptor(
  name='PolicyKey',
  full_name='edgeproto.PolicyKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='developer', full_name='edgeproto.PolicyKey.developer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='edgeproto.PolicyKey.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\370\363\030\001\260\240\037\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=155,
)


_AUTOSCALEPOLICY = _descriptor.Descriptor(
  name='AutoScalePolicy',
  full_name='edgeproto.AutoScalePolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='edgeproto.AutoScalePolicy.fields', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='edgeproto.AutoScalePolicy.key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_nodes', full_name='edgeproto.AutoScalePolicy.min_nodes', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_nodes', full_name='edgeproto.AutoScalePolicy.max_nodes', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale_up_cpu_thresh', full_name='edgeproto.AutoScalePolicy.scale_up_cpu_thresh', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale_down_cpu_thresh', full_name='edgeproto.AutoScalePolicy.scale_down_cpu_thresh', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trigger_time_sec', full_name='edgeproto.AutoScalePolicy.trigger_time_sec', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\210\364\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\360\363\030\001\230\364\030\001\200\364\030\001\220\364\030\001\232\365\030%name=Key.Name,developer=Key.Developer'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=425,
)

_AUTOSCALEPOLICY.fields_by_name['key'].message_type = _POLICYKEY
DESCRIPTOR.message_types_by_name['PolicyKey'] = _POLICYKEY
DESCRIPTOR.message_types_by_name['AutoScalePolicy'] = _AUTOSCALEPOLICY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PolicyKey = _reflection.GeneratedProtocolMessageType('PolicyKey', (_message.Message,), {
  'DESCRIPTOR' : _POLICYKEY,
  '__module__' : 'autoscalepolicy_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.PolicyKey)
  })
_sym_db.RegisterMessage(PolicyKey)

AutoScalePolicy = _reflection.GeneratedProtocolMessageType('AutoScalePolicy', (_message.Message,), {
  'DESCRIPTOR' : _AUTOSCALEPOLICY,
  '__module__' : 'autoscalepolicy_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.AutoScalePolicy)
  })
_sym_db.RegisterMessage(AutoScalePolicy)


_POLICYKEY._options = None
_AUTOSCALEPOLICY.fields_by_name['key']._options = None
_AUTOSCALEPOLICY.fields_by_name['trigger_time_sec']._options = None
_AUTOSCALEPOLICY._options = None

_AUTOSCALEPOLICYAPI = _descriptor.ServiceDescriptor(
  name='AutoScalePolicyApi',
  full_name='edgeproto.AutoScalePolicyApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=428,
  serialized_end=1126,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateAutoScalePolicy',
    full_name='edgeproto.AutoScalePolicyApi.CreateAutoScalePolicy',
    index=0,
    containing_service=None,
    input_type=_AUTOSCALEPOLICY,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\034\"\027/create/autoscalepolicy:\001*\352\364\0302ResourceDeveloperPolicy,ActionManage,Key.Developer\342\365\030\021MinNodes,MaxNodes'),
  ),
  _descriptor.MethodDescriptor(
    name='DeleteAutoScalePolicy',
    full_name='edgeproto.AutoScalePolicyApi.DeleteAutoScalePolicy',
    index=1,
    containing_service=None,
    input_type=_AUTOSCALEPOLICY,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\034\"\027/delete/autoscalepolicy:\001*\352\364\0302ResourceDeveloperPolicy,ActionManage,Key.Developer'),
  ),
  _descriptor.MethodDescriptor(
    name='UpdateAutoScalePolicy',
    full_name='edgeproto.AutoScalePolicyApi.UpdateAutoScalePolicy',
    index=2,
    containing_service=None,
    input_type=_AUTOSCALEPOLICY,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\034\"\027/update/autoscalepolicy:\001*\352\364\0302ResourceDeveloperPolicy,ActionManage,Key.Developer'),
  ),
  _descriptor.MethodDescriptor(
    name='ShowAutoScalePolicy',
    full_name='edgeproto.AutoScalePolicyApi.ShowAutoScalePolicy',
    index=3,
    containing_service=None,
    input_type=_AUTOSCALEPOLICY,
    output_type=_AUTOSCALEPOLICY,
    serialized_options=_b('\202\323\344\223\002\032\"\025/show/autoscalepolicy:\001*\352\364\0300ResourceDeveloperPolicy,ActionView,Key.Developer'),
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTOSCALEPOLICYAPI)

DESCRIPTOR.services_by_name['AutoScalePolicyApi'] = _AUTOSCALEPOLICYAPI

# @@protoc_insertion_point(module_scope)
