# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import autoscalepolicy_pb2 as autoscalepolicy__pb2
import result_pb2 as result__pb2


class AutoScalePolicyApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateAutoScalePolicy = channel.unary_unary(
        '/edgeproto.AutoScalePolicyApi/CreateAutoScalePolicy',
        request_serializer=autoscalepolicy__pb2.AutoScalePolicy.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.DeleteAutoScalePolicy = channel.unary_unary(
        '/edgeproto.AutoScalePolicyApi/DeleteAutoScalePolicy',
        request_serializer=autoscalepolicy__pb2.AutoScalePolicy.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.UpdateAutoScalePolicy = channel.unary_unary(
        '/edgeproto.AutoScalePolicyApi/UpdateAutoScalePolicy',
        request_serializer=autoscalepolicy__pb2.AutoScalePolicy.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ShowAutoScalePolicy = channel.unary_stream(
        '/edgeproto.AutoScalePolicyApi/ShowAutoScalePolicy',
        request_serializer=autoscalepolicy__pb2.AutoScalePolicy.SerializeToString,
        response_deserializer=autoscalepolicy__pb2.AutoScalePolicy.FromString,
        )


class AutoScalePolicyApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateAutoScalePolicy(self, request, context):
    """Create an Auto Scale Policy
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAutoScalePolicy(self, request, context):
    """Delete an Auto Scale Policy
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAutoScalePolicy(self, request, context):
    """Update an Auto Scale Policy
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowAutoScalePolicy(self, request, context):
    """Show Auto Scale Policies. Any fields specified will be used to filter results.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AutoScalePolicyApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateAutoScalePolicy': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAutoScalePolicy,
          request_deserializer=autoscalepolicy__pb2.AutoScalePolicy.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'DeleteAutoScalePolicy': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAutoScalePolicy,
          request_deserializer=autoscalepolicy__pb2.AutoScalePolicy.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'UpdateAutoScalePolicy': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAutoScalePolicy,
          request_deserializer=autoscalepolicy__pb2.AutoScalePolicy.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ShowAutoScalePolicy': grpc.unary_stream_rpc_method_handler(
          servicer.ShowAutoScalePolicy,
          request_deserializer=autoscalepolicy__pb2.AutoScalePolicy.FromString,
          response_serializer=autoscalepolicy__pb2.AutoScalePolicy.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.AutoScalePolicyApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
