# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cloudlet_pb2 as cloudlet__pb2
import cloudletpool_pb2 as cloudletpool__pb2
import result_pb2 as result__pb2


class CloudletPoolApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateCloudletPool = channel.unary_unary(
        '/edgeproto.CloudletPoolApi/CreateCloudletPool',
        request_serializer=cloudletpool__pb2.CloudletPool.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.DeleteCloudletPool = channel.unary_unary(
        '/edgeproto.CloudletPoolApi/DeleteCloudletPool',
        request_serializer=cloudletpool__pb2.CloudletPool.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ShowCloudletPool = channel.unary_stream(
        '/edgeproto.CloudletPoolApi/ShowCloudletPool',
        request_serializer=cloudletpool__pb2.CloudletPool.SerializeToString,
        response_deserializer=cloudletpool__pb2.CloudletPool.FromString,
        )


class CloudletPoolApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateCloudletPool(self, request, context):
    """Create a CloudletPool
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteCloudletPool(self, request, context):
    """Delete a CloudletPool
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowCloudletPool(self, request, context):
    """Show CloudletPools
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloudletPoolApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateCloudletPool': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCloudletPool,
          request_deserializer=cloudletpool__pb2.CloudletPool.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'DeleteCloudletPool': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteCloudletPool,
          request_deserializer=cloudletpool__pb2.CloudletPool.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ShowCloudletPool': grpc.unary_stream_rpc_method_handler(
          servicer.ShowCloudletPool,
          request_deserializer=cloudletpool__pb2.CloudletPool.FromString,
          response_serializer=cloudletpool__pb2.CloudletPool.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.CloudletPoolApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CloudletPoolMemberApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateCloudletPoolMember = channel.unary_unary(
        '/edgeproto.CloudletPoolMemberApi/CreateCloudletPoolMember',
        request_serializer=cloudletpool__pb2.CloudletPoolMember.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.DeleteCloudletPoolMember = channel.unary_unary(
        '/edgeproto.CloudletPoolMemberApi/DeleteCloudletPoolMember',
        request_serializer=cloudletpool__pb2.CloudletPoolMember.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ShowCloudletPoolMember = channel.unary_stream(
        '/edgeproto.CloudletPoolMemberApi/ShowCloudletPoolMember',
        request_serializer=cloudletpool__pb2.CloudletPoolMember.SerializeToString,
        response_deserializer=cloudletpool__pb2.CloudletPoolMember.FromString,
        )


class CloudletPoolMemberApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateCloudletPoolMember(self, request, context):
    """Add a Cloudlet to a CloudletPool
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteCloudletPoolMember(self, request, context):
    """Remove a Cloudlet from a CloudletPool
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowCloudletPoolMember(self, request, context):
    """Show the Cloudlet to CloudletPool relationships
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloudletPoolMemberApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateCloudletPoolMember': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCloudletPoolMember,
          request_deserializer=cloudletpool__pb2.CloudletPoolMember.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'DeleteCloudletPoolMember': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteCloudletPoolMember,
          request_deserializer=cloudletpool__pb2.CloudletPoolMember.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ShowCloudletPoolMember': grpc.unary_stream_rpc_method_handler(
          servicer.ShowCloudletPoolMember,
          request_deserializer=cloudletpool__pb2.CloudletPoolMember.FromString,
          response_serializer=cloudletpool__pb2.CloudletPoolMember.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.CloudletPoolMemberApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CloudletPoolShowApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ShowPoolsForCloudlet = channel.unary_stream(
        '/edgeproto.CloudletPoolShowApi/ShowPoolsForCloudlet',
        request_serializer=cloudlet__pb2.CloudletKey.SerializeToString,
        response_deserializer=cloudletpool__pb2.CloudletPool.FromString,
        )
    self.ShowCloudletsForPool = channel.unary_stream(
        '/edgeproto.CloudletPoolShowApi/ShowCloudletsForPool',
        request_serializer=cloudletpool__pb2.CloudletPoolKey.SerializeToString,
        response_deserializer=cloudlet__pb2.Cloudlet.FromString,
        )


class CloudletPoolShowApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ShowPoolsForCloudlet(self, request, context):
    """Show CloudletPools that have Cloudlet as a member
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowCloudletsForPool(self, request, context):
    """Show Cloudlets that belong to the Pool
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloudletPoolShowApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ShowPoolsForCloudlet': grpc.unary_stream_rpc_method_handler(
          servicer.ShowPoolsForCloudlet,
          request_deserializer=cloudlet__pb2.CloudletKey.FromString,
          response_serializer=cloudletpool__pb2.CloudletPool.SerializeToString,
      ),
      'ShowCloudletsForPool': grpc.unary_stream_rpc_method_handler(
          servicer.ShowCloudletsForPool,
          request_deserializer=cloudletpool__pb2.CloudletPoolKey.FromString,
          response_serializer=cloudlet__pb2.Cloudlet.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.CloudletPoolShowApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
