# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cloudlet_pb2 as cloudlet__pb2
import result_pb2 as result__pb2


class CloudletApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateCloudlet = channel.unary_stream(
        '/edgeproto.CloudletApi/CreateCloudlet',
        request_serializer=cloudlet__pb2.Cloudlet.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.DeleteCloudlet = channel.unary_stream(
        '/edgeproto.CloudletApi/DeleteCloudlet',
        request_serializer=cloudlet__pb2.Cloudlet.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.UpdateCloudlet = channel.unary_stream(
        '/edgeproto.CloudletApi/UpdateCloudlet',
        request_serializer=cloudlet__pb2.Cloudlet.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ShowCloudlet = channel.unary_stream(
        '/edgeproto.CloudletApi/ShowCloudlet',
        request_serializer=cloudlet__pb2.Cloudlet.SerializeToString,
        response_deserializer=cloudlet__pb2.Cloudlet.FromString,
        )
    self.AddCloudletResMapping = channel.unary_unary(
        '/edgeproto.CloudletApi/AddCloudletResMapping',
        request_serializer=cloudlet__pb2.CloudletResMap.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.RemoveCloudletResMapping = channel.unary_unary(
        '/edgeproto.CloudletApi/RemoveCloudletResMapping',
        request_serializer=cloudlet__pb2.CloudletResMap.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.FindFlavorMatch = channel.unary_unary(
        '/edgeproto.CloudletApi/FindFlavorMatch',
        request_serializer=cloudlet__pb2.FlavorMatch.SerializeToString,
        response_deserializer=cloudlet__pb2.FlavorMatch.FromString,
        )


class CloudletApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateCloudlet(self, request, context):
    """Create Cloudlet. Sets up Cloudlet services on the Operator's compute resources,
    and integrated as part of MobiledgeX edge resource portfolio.
    These resources are managed from the Edge Controller.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteCloudlet(self, request, context):
    """Delete Cloudlet. Removes the Cloudlet services where they are no longer managed
    from the Edge Controller.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateCloudlet(self, request, context):
    """Update Cloudlet. Updates the Cloudlet configuration and manages the upgrade of Cloudlet services.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowCloudlet(self, request, context):
    """Show Cloudlets. Lists all the cloudlets managed from Edge Controller.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddCloudletResMapping(self, request, context):
    """Add Optional Resource tag table
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveCloudletResMapping(self, request, context):
    """Add Optional Resource tag table
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindFlavorMatch(self, request, context):
    """Discover if flavor produces a matching platform flavor
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloudletApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateCloudlet': grpc.unary_stream_rpc_method_handler(
          servicer.CreateCloudlet,
          request_deserializer=cloudlet__pb2.Cloudlet.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'DeleteCloudlet': grpc.unary_stream_rpc_method_handler(
          servicer.DeleteCloudlet,
          request_deserializer=cloudlet__pb2.Cloudlet.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'UpdateCloudlet': grpc.unary_stream_rpc_method_handler(
          servicer.UpdateCloudlet,
          request_deserializer=cloudlet__pb2.Cloudlet.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ShowCloudlet': grpc.unary_stream_rpc_method_handler(
          servicer.ShowCloudlet,
          request_deserializer=cloudlet__pb2.Cloudlet.FromString,
          response_serializer=cloudlet__pb2.Cloudlet.SerializeToString,
      ),
      'AddCloudletResMapping': grpc.unary_unary_rpc_method_handler(
          servicer.AddCloudletResMapping,
          request_deserializer=cloudlet__pb2.CloudletResMap.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'RemoveCloudletResMapping': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveCloudletResMapping,
          request_deserializer=cloudlet__pb2.CloudletResMap.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'FindFlavorMatch': grpc.unary_unary_rpc_method_handler(
          servicer.FindFlavorMatch,
          request_deserializer=cloudlet__pb2.FlavorMatch.FromString,
          response_serializer=cloudlet__pb2.FlavorMatch.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.CloudletApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CloudletInfoApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ShowCloudletInfo = channel.unary_stream(
        '/edgeproto.CloudletInfoApi/ShowCloudletInfo',
        request_serializer=cloudlet__pb2.CloudletInfo.SerializeToString,
        response_deserializer=cloudlet__pb2.CloudletInfo.FromString,
        )
    self.InjectCloudletInfo = channel.unary_unary(
        '/edgeproto.CloudletInfoApi/InjectCloudletInfo',
        request_serializer=cloudlet__pb2.CloudletInfo.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.EvictCloudletInfo = channel.unary_unary(
        '/edgeproto.CloudletInfoApi/EvictCloudletInfo',
        request_serializer=cloudlet__pb2.CloudletInfo.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )


class CloudletInfoApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ShowCloudletInfo(self, request, context):
    """Show CloudletInfos
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InjectCloudletInfo(self, request, context):
    """Inject (create) a CloudletInfo for regression testing
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EvictCloudletInfo(self, request, context):
    """Evict (delete) a CloudletInfo for regression testing
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloudletInfoApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ShowCloudletInfo': grpc.unary_stream_rpc_method_handler(
          servicer.ShowCloudletInfo,
          request_deserializer=cloudlet__pb2.CloudletInfo.FromString,
          response_serializer=cloudlet__pb2.CloudletInfo.SerializeToString,
      ),
      'InjectCloudletInfo': grpc.unary_unary_rpc_method_handler(
          servicer.InjectCloudletInfo,
          request_deserializer=cloudlet__pb2.CloudletInfo.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'EvictCloudletInfo': grpc.unary_unary_rpc_method_handler(
          servicer.EvictCloudletInfo,
          request_deserializer=cloudlet__pb2.CloudletInfo.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.CloudletInfoApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class CloudletMetricsApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ShowCloudletMetrics = channel.unary_stream(
        '/edgeproto.CloudletMetricsApi/ShowCloudletMetrics',
        request_serializer=cloudlet__pb2.CloudletMetrics.SerializeToString,
        response_deserializer=cloudlet__pb2.CloudletMetrics.FromString,
        )


class CloudletMetricsApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ShowCloudletMetrics(self, request, context):
    """Show Cloudlet metrics
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloudletMetricsApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ShowCloudletMetrics': grpc.unary_stream_rpc_method_handler(
          servicer.ShowCloudletMetrics,
          request_deserializer=cloudlet__pb2.CloudletMetrics.FromString,
          response_serializer=cloudlet__pb2.CloudletMetrics.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.CloudletMetricsApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
