# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2
import protogen_pb2 as protogen__pb2
import result_pb2 as result__pb2
import developer_pb2 as developer__pb2
import flavor_pb2 as flavor__pb2
import gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cluster.proto',
  package='edgeproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rcluster.proto\x12\tedgeproto\x1a\x11\x61nnotations.proto\x1a\x0eprotogen.proto\x1a\x0cresult.proto\x1a\x0f\x64\x65veloper.proto\x1a\x0c\x66lavor.proto\x1a\ngogo.proto\"(\n\nClusterKey\x12\x0c\n\x04name\x18\x01 \x01(\t:\x0c\xe8\xf3\x18\x01\xf8\xf3\x18\x01\xb0\xa0\x1f\x01\x62\x06proto3')
  ,
  dependencies=[annotations__pb2.DESCRIPTOR,protogen__pb2.DESCRIPTOR,result__pb2.DESCRIPTOR,developer__pb2.DESCRIPTOR,flavor__pb2.DESCRIPTOR,gogo__pb2.DESCRIPTOR,])




_CLUSTERKEY = _descriptor.Descriptor(
  name='ClusterKey',
  full_name='edgeproto.ClusterKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='edgeproto.ClusterKey.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\370\363\030\001\260\240\037\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['ClusterKey'] = _CLUSTERKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClusterKey = _reflection.GeneratedProtocolMessageType('ClusterKey', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERKEY,
  '__module__' : 'cluster_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.ClusterKey)
  })
_sym_db.RegisterMessage(ClusterKey)


_CLUSTERKEY._options = None
# @@protoc_insertion_point(module_scope)
