# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='edgeproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\tedgeproto\x1a\x11\x61nnotations.proto\"Z\n\nStatusInfo\x12\x13\n\x0btask_number\x18\x01 \x01(\r\x12\x11\n\tmax_tasks\x18\x02 \x01(\r\x12\x11\n\ttask_name\x18\x03 \x01(\t\x12\x11\n\tstep_name\x18\x04 \x01(\t*K\n\x08Liveness\x12\x14\n\x10LIVENESS_UNKNOWN\x10\x00\x12\x13\n\x0fLIVENESS_STATIC\x10\x01\x12\x14\n\x10LIVENESS_DYNAMIC\x10\x02*R\n\tIpSupport\x12\x16\n\x12IP_SUPPORT_UNKNOWN\x10\x00\x12\x15\n\x11IP_SUPPORT_STATIC\x10\x01\x12\x16\n\x12IP_SUPPORT_DYNAMIC\x10\x02*P\n\x08IpAccess\x12\x15\n\x11IP_ACCESS_UNKNOWN\x10\x00\x12\x17\n\x13IP_ACCESS_DEDICATED\x10\x01\x12\x14\n\x10IP_ACCESS_SHARED\x10\x03*\xa6\x02\n\x0cTrackedState\x12\x19\n\x15TRACKED_STATE_UNKNOWN\x10\x00\x12\x0f\n\x0bNOT_PRESENT\x10\x01\x12\x14\n\x10\x43REATE_REQUESTED\x10\x02\x12\x0c\n\x08\x43REATING\x10\x03\x12\x10\n\x0c\x43REATE_ERROR\x10\x04\x12\t\n\x05READY\x10\x05\x12\x14\n\x10UPDATE_REQUESTED\x10\x06\x12\x0c\n\x08UPDATING\x10\x07\x12\x10\n\x0cUPDATE_ERROR\x10\x08\x12\x14\n\x10\x44\x45LETE_REQUESTED\x10\t\x12\x0c\n\x08\x44\x45LETING\x10\n\x12\x10\n\x0c\x44\x45LETE_ERROR\x10\x0b\x12\x12\n\x0e\x44\x45LETE_PREPARE\x10\x0c\x12\x0e\n\nCRM_INITOK\x10\r\x12\x19\n\x15\x43REATING_DEPENDENCIES\x10\x0e*\x85\x01\n\x0b\x43RMOverride\x12\x0f\n\x0bNO_OVERRIDE\x10\x00\x12\x15\n\x11IGNORE_CRM_ERRORS\x10\x01\x12\x0e\n\nIGNORE_CRM\x10\x02\x12\x1a\n\x16IGNORE_TRANSIENT_STATE\x10\x03\x12\"\n\x1eIGNORE_CRM_AND_TRANSIENT_STATE\x10\x04\x62\x06proto3')
  ,
  dependencies=[annotations__pb2.DESCRIPTOR,])

_LIVENESS = _descriptor.EnumDescriptor(
  name='Liveness',
  full_name='edgeproto.Liveness',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIVENESS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIVENESS_STATIC', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIVENESS_DYNAMIC', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=138,
  serialized_end=213,
)
_sym_db.RegisterEnumDescriptor(_LIVENESS)

Liveness = enum_type_wrapper.EnumTypeWrapper(_LIVENESS)
_IPSUPPORT = _descriptor.EnumDescriptor(
  name='IpSupport',
  full_name='edgeproto.IpSupport',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IP_SUPPORT_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IP_SUPPORT_STATIC', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IP_SUPPORT_DYNAMIC', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=215,
  serialized_end=297,
)
_sym_db.RegisterEnumDescriptor(_IPSUPPORT)

IpSupport = enum_type_wrapper.EnumTypeWrapper(_IPSUPPORT)
_IPACCESS = _descriptor.EnumDescriptor(
  name='IpAccess',
  full_name='edgeproto.IpAccess',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IP_ACCESS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IP_ACCESS_DEDICATED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IP_ACCESS_SHARED', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=299,
  serialized_end=379,
)
_sym_db.RegisterEnumDescriptor(_IPACCESS)

IpAccess = enum_type_wrapper.EnumTypeWrapper(_IPACCESS)
_TRACKEDSTATE = _descriptor.EnumDescriptor(
  name='TrackedState',
  full_name='edgeproto.TrackedState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRACKED_STATE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_PRESENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_REQUESTED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATING', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ERROR', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_REQUESTED', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATING', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_ERROR', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_REQUESTED', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETING', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_ERROR', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_PREPARE', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRM_INITOK', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATING_DEPENDENCIES', index=14, number=14,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=382,
  serialized_end=676,
)
_sym_db.RegisterEnumDescriptor(_TRACKEDSTATE)

TrackedState = enum_type_wrapper.EnumTypeWrapper(_TRACKEDSTATE)
_CRMOVERRIDE = _descriptor.EnumDescriptor(
  name='CRMOverride',
  full_name='edgeproto.CRMOverride',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_OVERRIDE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IGNORE_CRM_ERRORS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IGNORE_CRM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IGNORE_TRANSIENT_STATE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IGNORE_CRM_AND_TRANSIENT_STATE', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=679,
  serialized_end=812,
)
_sym_db.RegisterEnumDescriptor(_CRMOVERRIDE)

CRMOverride = enum_type_wrapper.EnumTypeWrapper(_CRMOVERRIDE)
LIVENESS_UNKNOWN = 0
LIVENESS_STATIC = 1
LIVENESS_DYNAMIC = 2
IP_SUPPORT_UNKNOWN = 0
IP_SUPPORT_STATIC = 1
IP_SUPPORT_DYNAMIC = 2
IP_ACCESS_UNKNOWN = 0
IP_ACCESS_DEDICATED = 1
IP_ACCESS_SHARED = 3
TRACKED_STATE_UNKNOWN = 0
NOT_PRESENT = 1
CREATE_REQUESTED = 2
CREATING = 3
CREATE_ERROR = 4
READY = 5
UPDATE_REQUESTED = 6
UPDATING = 7
UPDATE_ERROR = 8
DELETE_REQUESTED = 9
DELETING = 10
DELETE_ERROR = 11
DELETE_PREPARE = 12
CRM_INITOK = 13
CREATING_DEPENDENCIES = 14
NO_OVERRIDE = 0
IGNORE_CRM_ERRORS = 1
IGNORE_CRM = 2
IGNORE_TRANSIENT_STATE = 3
IGNORE_CRM_AND_TRANSIENT_STATE = 4



_STATUSINFO = _descriptor.Descriptor(
  name='StatusInfo',
  full_name='edgeproto.StatusInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_number', full_name='edgeproto.StatusInfo.task_number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_tasks', full_name='edgeproto.StatusInfo.max_tasks', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_name', full_name='edgeproto.StatusInfo.task_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step_name', full_name='edgeproto.StatusInfo.step_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['StatusInfo'] = _STATUSINFO
DESCRIPTOR.enum_types_by_name['Liveness'] = _LIVENESS
DESCRIPTOR.enum_types_by_name['IpSupport'] = _IPSUPPORT
DESCRIPTOR.enum_types_by_name['IpAccess'] = _IPACCESS
DESCRIPTOR.enum_types_by_name['TrackedState'] = _TRACKEDSTATE
DESCRIPTOR.enum_types_by_name['CRMOverride'] = _CRMOVERRIDE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusInfo = _reflection.GeneratedProtocolMessageType('StatusInfo', (_message.Message,), {
  'DESCRIPTOR' : _STATUSINFO,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.StatusInfo)
  })
_sym_db.RegisterMessage(StatusInfo)


# @@protoc_insertion_point(module_scope)
