# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flavor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2
import protogen_pb2 as protogen__pb2
import result_pb2 as result__pb2
import gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='flavor.proto',
  package='edgeproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x66lavor.proto\x12\tedgeproto\x1a\x11\x61nnotations.proto\x1a\x0eprotogen.proto\x1a\x0cresult.proto\x1a\ngogo.proto\"\'\n\tFlavorKey\x12\x0c\n\x04name\x18\x01 \x01(\t:\x0c\xe8\xf3\x18\x01\xf8\xf3\x18\x01\xb0\xa0\x1f\x01\"\xfb\x01\n\x06\x46lavor\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\x12\'\n\x03key\x18\x02 \x01(\x0b\x32\x14.edgeproto.FlavorKeyB\x04\xc8\xde\x1f\x00\x12\x0b\n\x03ram\x18\x03 \x01(\x04\x12\r\n\x05vcpus\x18\x04 \x01(\x04\x12\x0c\n\x04\x64isk\x18\x05 \x01(\x04\x12\x35\n\x0bopt_res_map\x18\x06 \x03(\x0b\x32 .edgeproto.Flavor.OptResMapEntry\x1a\x30\n\x0eOptResMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01:%\xe8\xf3\x18\x01\xf0\xf3\x18\x01\x98\xf4\x18\x01\x80\xf4\x18\x01\x90\xf4\x18\x01\x9a\xf5\x18\rname=Key.Name2\xd7\x05\n\tFlavorApi\x12\x82\x01\n\x0c\x43reateFlavor\x12\x11.edgeproto.Flavor\x1a\x11.edgeproto.Result\"L\x82\xd3\xe4\x93\x02\x13\"\x0e/create/flavor:\x01*\xea\xf4\x18\x1dResourceFlavors,ActionManage,\xe2\xf5\x18\x0eRam,Vcpus,Disk\x12p\n\x0c\x44\x65leteFlavor\x12\x11.edgeproto.Flavor\x1a\x11.edgeproto.Result\":\x82\xd3\xe4\x93\x02\x13\"\x0e/delete/flavor:\x01*\xea\xf4\x18\x1dResourceFlavors,ActionManage,\x12p\n\x0cUpdateFlavor\x12\x11.edgeproto.Flavor\x1a\x11.edgeproto.Result\":\x82\xd3\xe4\x93\x02\x13\"\x0e/update/flavor:\x01*\xea\xf4\x18\x1dResourceFlavors,ActionManage,\x12w\n\nShowFlavor\x12\x11.edgeproto.Flavor\x1a\x11.edgeproto.Flavor\"A\x82\xd3\xe4\x93\x02\x11\"\x0c/show/flavor:\x01*\xea\xf4\x18&ResourceFlavors,ActionView,skipenforce0\x01\x12p\n\x0c\x41\x64\x64\x46lavorRes\x12\x11.edgeproto.Flavor\x1a\x11.edgeproto.Result\":\x82\xd3\xe4\x93\x02\x13\"\x0e/addres/flavor:\x01*\xea\xf4\x18\x1dResourceFlavors,ActionManage,\x12v\n\x0fRemoveFlavorRes\x12\x11.edgeproto.Flavor\x1a\x11.edgeproto.Result\"=\x82\xd3\xe4\x93\x02\x16\"\x11/removeres/flavor:\x01*\xea\xf4\x18\x1dResourceFlavors,ActionManage,b\x06proto3')
  ,
  dependencies=[annotations__pb2.DESCRIPTOR,protogen__pb2.DESCRIPTOR,result__pb2.DESCRIPTOR,gogo__pb2.DESCRIPTOR,])




_FLAVORKEY = _descriptor.Descriptor(
  name='FlavorKey',
  full_name='edgeproto.FlavorKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='edgeproto.FlavorKey.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\370\363\030\001\260\240\037\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=127,
)


_FLAVOR_OPTRESMAPENTRY = _descriptor.Descriptor(
  name='OptResMapEntry',
  full_name='edgeproto.Flavor.OptResMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='edgeproto.Flavor.OptResMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='edgeproto.Flavor.OptResMapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=342,
)

_FLAVOR = _descriptor.Descriptor(
  name='Flavor',
  full_name='edgeproto.Flavor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='edgeproto.Flavor.fields', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='edgeproto.Flavor.key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ram', full_name='edgeproto.Flavor.ram', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vcpus', full_name='edgeproto.Flavor.vcpus', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk', full_name='edgeproto.Flavor.disk', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opt_res_map', full_name='edgeproto.Flavor.opt_res_map', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FLAVOR_OPTRESMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\360\363\030\001\230\364\030\001\200\364\030\001\220\364\030\001\232\365\030\rname=Key.Name'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=381,
)

_FLAVOR_OPTRESMAPENTRY.containing_type = _FLAVOR
_FLAVOR.fields_by_name['key'].message_type = _FLAVORKEY
_FLAVOR.fields_by_name['opt_res_map'].message_type = _FLAVOR_OPTRESMAPENTRY
DESCRIPTOR.message_types_by_name['FlavorKey'] = _FLAVORKEY
DESCRIPTOR.message_types_by_name['Flavor'] = _FLAVOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlavorKey = _reflection.GeneratedProtocolMessageType('FlavorKey', (_message.Message,), {
  'DESCRIPTOR' : _FLAVORKEY,
  '__module__' : 'flavor_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.FlavorKey)
  })
_sym_db.RegisterMessage(FlavorKey)

Flavor = _reflection.GeneratedProtocolMessageType('Flavor', (_message.Message,), {

  'OptResMapEntry' : _reflection.GeneratedProtocolMessageType('OptResMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _FLAVOR_OPTRESMAPENTRY,
    '__module__' : 'flavor_pb2'
    # @@protoc_insertion_point(class_scope:edgeproto.Flavor.OptResMapEntry)
    })
  ,
  'DESCRIPTOR' : _FLAVOR,
  '__module__' : 'flavor_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.Flavor)
  })
_sym_db.RegisterMessage(Flavor)
_sym_db.RegisterMessage(Flavor.OptResMapEntry)


_FLAVORKEY._options = None
_FLAVOR_OPTRESMAPENTRY._options = None
_FLAVOR.fields_by_name['key']._options = None
_FLAVOR._options = None

_FLAVORAPI = _descriptor.ServiceDescriptor(
  name='FlavorApi',
  full_name='edgeproto.FlavorApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=384,
  serialized_end=1111,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateFlavor',
    full_name='edgeproto.FlavorApi.CreateFlavor',
    index=0,
    containing_service=None,
    input_type=_FLAVOR,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\023\"\016/create/flavor:\001*\352\364\030\035ResourceFlavors,ActionManage,\342\365\030\016Ram,Vcpus,Disk'),
  ),
  _descriptor.MethodDescriptor(
    name='DeleteFlavor',
    full_name='edgeproto.FlavorApi.DeleteFlavor',
    index=1,
    containing_service=None,
    input_type=_FLAVOR,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\023\"\016/delete/flavor:\001*\352\364\030\035ResourceFlavors,ActionManage,'),
  ),
  _descriptor.MethodDescriptor(
    name='UpdateFlavor',
    full_name='edgeproto.FlavorApi.UpdateFlavor',
    index=2,
    containing_service=None,
    input_type=_FLAVOR,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\023\"\016/update/flavor:\001*\352\364\030\035ResourceFlavors,ActionManage,'),
  ),
  _descriptor.MethodDescriptor(
    name='ShowFlavor',
    full_name='edgeproto.FlavorApi.ShowFlavor',
    index=3,
    containing_service=None,
    input_type=_FLAVOR,
    output_type=_FLAVOR,
    serialized_options=_b('\202\323\344\223\002\021\"\014/show/flavor:\001*\352\364\030&ResourceFlavors,ActionView,skipenforce'),
  ),
  _descriptor.MethodDescriptor(
    name='AddFlavorRes',
    full_name='edgeproto.FlavorApi.AddFlavorRes',
    index=4,
    containing_service=None,
    input_type=_FLAVOR,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\023\"\016/addres/flavor:\001*\352\364\030\035ResourceFlavors,ActionManage,'),
  ),
  _descriptor.MethodDescriptor(
    name='RemoveFlavorRes',
    full_name='edgeproto.FlavorApi.RemoveFlavorRes',
    index=5,
    containing_service=None,
    input_type=_FLAVOR,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\026\"\021/removeres/flavor:\001*\352\364\030\035ResourceFlavors,ActionManage,'),
  ),
])
_sym_db.RegisterServiceDescriptor(_FLAVORAPI)

DESCRIPTOR.services_by_name['FlavorApi'] = _FLAVORAPI

# @@protoc_insertion_point(module_scope)
