# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2
import cloudlet_pb2 as cloudlet__pb2
import gogo_pb2 as gogo__pb2
import protogen_pb2 as protogen__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='node.proto',
  package='edgeproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nnode.proto\x12\tedgeproto\x1a\x11\x61nnotations.proto\x1a\x0e\x63loudlet.proto\x1a\ngogo.proto\x1a\x0eprotogen.proto\"\x8c\x01\n\x07NodeKey\x12\x17\n\x04name\x18\x01 \x01(\tB\t\x92\xb2\x19\x05nocmp\x12&\n\tnode_type\x18\x02 \x01(\x0e\x32\x13.edgeproto.NodeType\x12\x32\n\x0c\x63loudlet_key\x18\x03 \x01(\x0b\x32\x16.edgeproto.CloudletKeyB\x04\xc8\xde\x1f\x00:\x0c\xe8\xf3\x18\x01\xf8\xf3\x18\x01\xb0\xa0\x1f\x01\"\xa8\x02\n\x04Node\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\x12%\n\x03key\x18\x02 \x01(\x0b\x32\x12.edgeproto.NodeKeyB\x04\xc8\xde\x1f\x00\x12 \n\tnotify_id\x18\x03 \x01(\x03\x42\r\xa8\xf4\x18\x01\x92\xb2\x19\x05nocmp\x12#\n\x0c\x62uild_master\x18\x04 \x01(\tB\r\xa8\xf4\x18\x01\x92\xb2\x19\x05nocmp\x12!\n\nbuild_head\x18\x05 \x01(\tB\r\xa8\xf4\x18\x01\x92\xb2\x19\x05nocmp\x12#\n\x0c\x62uild_author\x18\x06 \x01(\tB\r\xa8\xf4\x18\x01\x92\xb2\x19\x05nocmp\x12\x1f\n\x08hostname\x18\x07 \x01(\tB\r\xa8\xf4\x18\x01\x92\xb2\x19\x05nocmp\x12\x1f\n\x11\x63ontainer_version\x18\x08 \x01(\tB\x04\xa8\xf4\x18\x01:\x18\xe8\xf3\x18\x01\xf0\xf3\x18\x01\x80\xf4\x18\x01\xa0\xf4\x18\x01\x90\xf4\x18\x01\xe0\xf4\x18\x01*M\n\x08NodeType\x12\x10\n\x0cNODE_UNKNOWN\x10\x00\x12\x0c\n\x08NODE_DME\x10\x01\x12\x0c\n\x08NODE_CRM\x10\x02\x12\x13\n\x0fNODE_CONTROLLER\x10\x03\x32\xbf\x01\n\x07NodeApi\x12O\n\rShowNodeLocal\x12\x0f.edgeproto.Node\x1a\x0f.edgeproto.Node\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x0f/show/nodelocal:\x01*0\x01\x12\x63\n\x08ShowNode\x12\x0f.edgeproto.Node\x1a\x0f.edgeproto.Node\"3\x82\xd3\xe4\x93\x02\x0f\"\n/show/node:\x01*\xea\xf4\x18\x1aResourceConfig,ActionView,0\x01\x62\x06proto3')
  ,
  dependencies=[annotations__pb2.DESCRIPTOR,cloudlet__pb2.DESCRIPTOR,gogo__pb2.DESCRIPTOR,protogen__pb2.DESCRIPTOR,])

_NODETYPE = _descriptor.EnumDescriptor(
  name='NodeType',
  full_name='edgeproto.NodeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NODE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NODE_DME', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NODE_CRM', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NODE_CONTROLLER', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=530,
  serialized_end=607,
)
_sym_db.RegisterEnumDescriptor(_NODETYPE)

NodeType = enum_type_wrapper.EnumTypeWrapper(_NODETYPE)
NODE_UNKNOWN = 0
NODE_DME = 1
NODE_CRM = 2
NODE_CONTROLLER = 3



_NODEKEY = _descriptor.Descriptor(
  name='NodeKey',
  full_name='edgeproto.NodeKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='edgeproto.NodeKey.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222\262\031\005nocmp'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_type', full_name='edgeproto.NodeKey.node_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cloudlet_key', full_name='edgeproto.NodeKey.cloudlet_key', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\370\363\030\001\260\240\037\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=229,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='edgeproto.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='edgeproto.Node.fields', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='edgeproto.Node.key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notify_id', full_name='edgeproto.Node.notify_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\250\364\030\001\222\262\031\005nocmp'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_master', full_name='edgeproto.Node.build_master', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\250\364\030\001\222\262\031\005nocmp'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_head', full_name='edgeproto.Node.build_head', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\250\364\030\001\222\262\031\005nocmp'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_author', full_name='edgeproto.Node.build_author', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\250\364\030\001\222\262\031\005nocmp'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='edgeproto.Node.hostname', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\250\364\030\001\222\262\031\005nocmp'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='container_version', full_name='edgeproto.Node.container_version', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\250\364\030\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\360\363\030\001\200\364\030\001\240\364\030\001\220\364\030\001\340\364\030\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=528,
)

_NODEKEY.fields_by_name['node_type'].enum_type = _NODETYPE
_NODEKEY.fields_by_name['cloudlet_key'].message_type = cloudlet__pb2._CLOUDLETKEY
_NODE.fields_by_name['key'].message_type = _NODEKEY
DESCRIPTOR.message_types_by_name['NodeKey'] = _NODEKEY
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.enum_types_by_name['NodeType'] = _NODETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeKey = _reflection.GeneratedProtocolMessageType('NodeKey', (_message.Message,), {
  'DESCRIPTOR' : _NODEKEY,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.NodeKey)
  })
_sym_db.RegisterMessage(NodeKey)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.Node)
  })
_sym_db.RegisterMessage(Node)


_NODEKEY.fields_by_name['name']._options = None
_NODEKEY.fields_by_name['cloudlet_key']._options = None
_NODEKEY._options = None
_NODE.fields_by_name['key']._options = None
_NODE.fields_by_name['notify_id']._options = None
_NODE.fields_by_name['build_master']._options = None
_NODE.fields_by_name['build_head']._options = None
_NODE.fields_by_name['build_author']._options = None
_NODE.fields_by_name['hostname']._options = None
_NODE.fields_by_name['container_version']._options = None
_NODE._options = None

_NODEAPI = _descriptor.ServiceDescriptor(
  name='NodeApi',
  full_name='edgeproto.NodeApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=610,
  serialized_end=801,
  methods=[
  _descriptor.MethodDescriptor(
    name='ShowNodeLocal',
    full_name='edgeproto.NodeApi.ShowNodeLocal',
    index=0,
    containing_service=None,
    input_type=_NODE,
    output_type=_NODE,
    serialized_options=_b('\202\323\344\223\002\024\"\017/show/nodelocal:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='ShowNode',
    full_name='edgeproto.NodeApi.ShowNode',
    index=1,
    containing_service=None,
    input_type=_NODE,
    output_type=_NODE,
    serialized_options=_b('\202\323\344\223\002\017\"\n/show/node:\001*\352\364\030\032ResourceConfig,ActionView,'),
  ),
])
_sym_db.RegisterServiceDescriptor(_NODEAPI)

DESCRIPTOR.services_by_name['NodeApi'] = _NODEAPI

# @@protoc_insertion_point(module_scope)
