# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import operator_pb2 as operator__pb2
import result_pb2 as result__pb2


class OperatorApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateOperator = channel.unary_unary(
        '/edgeproto.OperatorApi/CreateOperator',
        request_serializer=operator__pb2.Operator.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.DeleteOperator = channel.unary_unary(
        '/edgeproto.OperatorApi/DeleteOperator',
        request_serializer=operator__pb2.Operator.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.UpdateOperator = channel.unary_unary(
        '/edgeproto.OperatorApi/UpdateOperator',
        request_serializer=operator__pb2.Operator.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ShowOperator = channel.unary_stream(
        '/edgeproto.OperatorApi/ShowOperator',
        request_serializer=operator__pb2.Operator.SerializeToString,
        response_deserializer=operator__pb2.Operator.FromString,
        )


class OperatorApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateOperator(self, request, context):
    """Create an Operator
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteOperator(self, request, context):
    """Delete an Operator
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOperator(self, request, context):
    """Update an Operator
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowOperator(self, request, context):
    """Show Operators
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OperatorApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateOperator': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOperator,
          request_deserializer=operator__pb2.Operator.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'DeleteOperator': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteOperator,
          request_deserializer=operator__pb2.Operator.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'UpdateOperator': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOperator,
          request_deserializer=operator__pb2.Operator.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ShowOperator': grpc.unary_stream_rpc_method_handler(
          servicer.ShowOperator,
          request_deserializer=operator__pb2.Operator.FromString,
          response_serializer=operator__pb2.Operator.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.OperatorApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class OperatorCodeApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateOperatorCode = channel.unary_unary(
        '/edgeproto.OperatorCodeApi/CreateOperatorCode',
        request_serializer=operator__pb2.OperatorCode.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.DeleteOperatorCode = channel.unary_unary(
        '/edgeproto.OperatorCodeApi/DeleteOperatorCode',
        request_serializer=operator__pb2.OperatorCode.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ShowOperatorCode = channel.unary_stream(
        '/edgeproto.OperatorCodeApi/ShowOperatorCode',
        request_serializer=operator__pb2.OperatorCode.SerializeToString,
        response_deserializer=operator__pb2.OperatorCode.FromString,
        )


class OperatorCodeApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateOperatorCode(self, request, context):
    """Create a code for an Operator.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteOperatorCode(self, request, context):
    """Delete a code for an Operator.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowOperatorCode(self, request, context):
    """Show OperatorCodes
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OperatorCodeApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateOperatorCode': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOperatorCode,
          request_deserializer=operator__pb2.OperatorCode.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'DeleteOperatorCode': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteOperatorCode,
          request_deserializer=operator__pb2.OperatorCode.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ShowOperatorCode': grpc.unary_stream_rpc_method_handler(
          servicer.ShowOperatorCode,
          request_deserializer=operator__pb2.OperatorCode.FromString,
          response_serializer=operator__pb2.OperatorCode.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.OperatorCodeApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
