# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2
import protogen_pb2 as protogen__pb2
import result_pb2 as result__pb2
import gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='operator.proto',
  package='edgeproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eoperator.proto\x12\tedgeproto\x1a\x11\x61nnotations.proto\x1a\x0eprotogen.proto\x1a\x0cresult.proto\x1a\ngogo.proto\")\n\x0bOperatorKey\x12\x0c\n\x04name\x18\x01 \x01(\t:\x0c\xe8\xf3\x18\x01\xf8\xf3\x18\x01\xb0\xa0\x1f\x01\"h\n\x08Operator\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\x12)\n\x03key\x18\x02 \x01(\x0b\x32\x16.edgeproto.OperatorKeyB\x04\xc8\xde\x1f\x00:!\xe8\xf3\x18\x01\xf0\xf3\x18\x01\x98\xf4\x18\x01\x80\xf4\x18\x01\x9a\xf5\x18\rname=Key.Name\"`\n\x0cOperatorCode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x15\n\roperator_name\x18\x02 \x01(\t:+\xe8\xf3\x18\x01\xf0\xf3\x18\x01\x98\xf4\x18\x01\xb0\xf5\x18\x00\x80\xf4\x18\x01\x90\xf4\x18\x01\xf2\xf5\x18\x0fOperatorCodeKey2\xe9\x02\n\x0bOperatorApi\x12U\n\x0e\x43reateOperator\x12\x13.edgeproto.Operator\x1a\x11.edgeproto.Result\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/create/operator:\x01*\x12U\n\x0e\x44\x65leteOperator\x12\x13.edgeproto.Operator\x1a\x11.edgeproto.Result\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/delete/operator:\x01*\x12U\n\x0eUpdateOperator\x12\x13.edgeproto.Operator\x1a\x11.edgeproto.Result\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/update/operator:\x01*\x12U\n\x0cShowOperator\x12\x13.edgeproto.Operator\x1a\x13.edgeproto.Operator\"\x19\x82\xd3\xe4\x93\x02\x13\"\x0e/show/operator:\x01*0\x01\x32\xb4\x03\n\x0fOperatorCodeApi\x12\x88\x01\n\x12\x43reateOperatorCode\x12\x17.edgeproto.OperatorCode\x1a\x11.edgeproto.Result\"F\x82\xd3\xe4\x93\x02\x19\"\x14/create/operatorcode:\x01*\xea\xf4\x18#ResourceCloudletPools,ActionManage,\x12\x88\x01\n\x12\x44\x65leteOperatorCode\x12\x17.edgeproto.OperatorCode\x1a\x11.edgeproto.Result\"F\x82\xd3\xe4\x93\x02\x19\"\x14/delete/operatorcode:\x01*\xea\xf4\x18#ResourceCloudletPools,ActionManage,\x12\x8a\x01\n\x10ShowOperatorCode\x12\x17.edgeproto.OperatorCode\x1a\x17.edgeproto.OperatorCode\"B\x82\xd3\xe4\x93\x02\x17\"\x12/show/operatorcode:\x01*\xea\xf4\x18!ResourceCloudletPools,ActionView,0\x01\x62\x06proto3')
  ,
  dependencies=[annotations__pb2.DESCRIPTOR,protogen__pb2.DESCRIPTOR,result__pb2.DESCRIPTOR,gogo__pb2.DESCRIPTOR,])




_OPERATORKEY = _descriptor.Descriptor(
  name='OperatorKey',
  full_name='edgeproto.OperatorKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='edgeproto.OperatorKey.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\370\363\030\001\260\240\037\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=131,
)


_OPERATOR = _descriptor.Descriptor(
  name='Operator',
  full_name='edgeproto.Operator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='edgeproto.Operator.fields', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='edgeproto.Operator.key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\360\363\030\001\230\364\030\001\200\364\030\001\232\365\030\rname=Key.Name'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=237,
)


_OPERATORCODE = _descriptor.Descriptor(
  name='OperatorCode',
  full_name='edgeproto.OperatorCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='edgeproto.OperatorCode.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operator_name', full_name='edgeproto.OperatorCode.operator_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\360\363\030\001\230\364\030\001\260\365\030\000\200\364\030\001\220\364\030\001\362\365\030\017OperatorCodeKey'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=335,
)

_OPERATOR.fields_by_name['key'].message_type = _OPERATORKEY
DESCRIPTOR.message_types_by_name['OperatorKey'] = _OPERATORKEY
DESCRIPTOR.message_types_by_name['Operator'] = _OPERATOR
DESCRIPTOR.message_types_by_name['OperatorCode'] = _OPERATORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OperatorKey = _reflection.GeneratedProtocolMessageType('OperatorKey', (_message.Message,), {
  'DESCRIPTOR' : _OPERATORKEY,
  '__module__' : 'operator_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.OperatorKey)
  })
_sym_db.RegisterMessage(OperatorKey)

Operator = _reflection.GeneratedProtocolMessageType('Operator', (_message.Message,), {
  'DESCRIPTOR' : _OPERATOR,
  '__module__' : 'operator_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.Operator)
  })
_sym_db.RegisterMessage(Operator)

OperatorCode = _reflection.GeneratedProtocolMessageType('OperatorCode', (_message.Message,), {
  'DESCRIPTOR' : _OPERATORCODE,
  '__module__' : 'operator_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.OperatorCode)
  })
_sym_db.RegisterMessage(OperatorCode)


_OPERATORKEY._options = None
_OPERATOR.fields_by_name['key']._options = None
_OPERATOR._options = None
_OPERATORCODE._options = None

_OPERATORAPI = _descriptor.ServiceDescriptor(
  name='OperatorApi',
  full_name='edgeproto.OperatorApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=338,
  serialized_end=699,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateOperator',
    full_name='edgeproto.OperatorApi.CreateOperator',
    index=0,
    containing_service=None,
    input_type=_OPERATOR,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\025\"\020/create/operator:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='DeleteOperator',
    full_name='edgeproto.OperatorApi.DeleteOperator',
    index=1,
    containing_service=None,
    input_type=_OPERATOR,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\025\"\020/delete/operator:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='UpdateOperator',
    full_name='edgeproto.OperatorApi.UpdateOperator',
    index=2,
    containing_service=None,
    input_type=_OPERATOR,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\025\"\020/update/operator:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='ShowOperator',
    full_name='edgeproto.OperatorApi.ShowOperator',
    index=3,
    containing_service=None,
    input_type=_OPERATOR,
    output_type=_OPERATOR,
    serialized_options=_b('\202\323\344\223\002\023\"\016/show/operator:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_OPERATORAPI)

DESCRIPTOR.services_by_name['OperatorApi'] = _OPERATORAPI


_OPERATORCODEAPI = _descriptor.ServiceDescriptor(
  name='OperatorCodeApi',
  full_name='edgeproto.OperatorCodeApi',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=702,
  serialized_end=1138,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateOperatorCode',
    full_name='edgeproto.OperatorCodeApi.CreateOperatorCode',
    index=0,
    containing_service=None,
    input_type=_OPERATORCODE,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\031\"\024/create/operatorcode:\001*\352\364\030#ResourceCloudletPools,ActionManage,'),
  ),
  _descriptor.MethodDescriptor(
    name='DeleteOperatorCode',
    full_name='edgeproto.OperatorCodeApi.DeleteOperatorCode',
    index=1,
    containing_service=None,
    input_type=_OPERATORCODE,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\031\"\024/delete/operatorcode:\001*\352\364\030#ResourceCloudletPools,ActionManage,'),
  ),
  _descriptor.MethodDescriptor(
    name='ShowOperatorCode',
    full_name='edgeproto.OperatorCodeApi.ShowOperatorCode',
    index=2,
    containing_service=None,
    input_type=_OPERATORCODE,
    output_type=_OPERATORCODE,
    serialized_options=_b('\202\323\344\223\002\027\"\022/show/operatorcode:\001*\352\364\030!ResourceCloudletPools,ActionView,'),
  ),
])
_sym_db.RegisterServiceDescriptor(_OPERATORCODEAPI)

DESCRIPTOR.services_by_name['OperatorCodeApi'] = _OPERATORCODEAPI

# @@protoc_insertion_point(module_scope)
