# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import privacypolicy_pb2 as privacypolicy__pb2
import result_pb2 as result__pb2


class PrivacyPolicyApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreatePrivacyPolicy = channel.unary_unary(
        '/edgeproto.PrivacyPolicyApi/CreatePrivacyPolicy',
        request_serializer=privacypolicy__pb2.PrivacyPolicy.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.DeletePrivacyPolicy = channel.unary_unary(
        '/edgeproto.PrivacyPolicyApi/DeletePrivacyPolicy',
        request_serializer=privacypolicy__pb2.PrivacyPolicy.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.UpdatePrivacyPolicy = channel.unary_unary(
        '/edgeproto.PrivacyPolicyApi/UpdatePrivacyPolicy',
        request_serializer=privacypolicy__pb2.PrivacyPolicy.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ShowPrivacyPolicy = channel.unary_stream(
        '/edgeproto.PrivacyPolicyApi/ShowPrivacyPolicy',
        request_serializer=privacypolicy__pb2.PrivacyPolicy.SerializeToString,
        response_deserializer=privacypolicy__pb2.PrivacyPolicy.FromString,
        )


class PrivacyPolicyApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreatePrivacyPolicy(self, request, context):
    """Create a Privacy Policy
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeletePrivacyPolicy(self, request, context):
    """Delete a Privacy policy
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePrivacyPolicy(self, request, context):
    """Update a Privacy policy
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowPrivacyPolicy(self, request, context):
    """Show Privacy Policies. Any fields specified will be used to filter results.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PrivacyPolicyApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreatePrivacyPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePrivacyPolicy,
          request_deserializer=privacypolicy__pb2.PrivacyPolicy.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'DeletePrivacyPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.DeletePrivacyPolicy,
          request_deserializer=privacypolicy__pb2.PrivacyPolicy.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'UpdatePrivacyPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePrivacyPolicy,
          request_deserializer=privacypolicy__pb2.PrivacyPolicy.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ShowPrivacyPolicy': grpc.unary_stream_rpc_method_handler(
          servicer.ShowPrivacyPolicy,
          request_deserializer=privacypolicy__pb2.PrivacyPolicy.FromString,
          response_serializer=privacypolicy__pb2.PrivacyPolicy.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.PrivacyPolicyApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
