# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: privacypolicy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2
import result_pb2 as result__pb2
import protogen_pb2 as protogen__pb2
import gogo_pb2 as gogo__pb2
import autoscalepolicy_pb2 as autoscalepolicy__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='privacypolicy.proto',
  package='edgeproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13privacypolicy.proto\x12\tedgeproto\x1a\x11\x61nnotations.proto\x1a\x0cresult.proto\x1a\x0eprotogen.proto\x1a\ngogo.proto\x1a\x15\x61utoscalepolicy.proto\"m\n\x14OutboundSecurityRule\x12\x10\n\x08protocol\x18\x01 \x01(\t\x12\x16\n\x0eport_range_min\x18\x02 \x01(\r\x12\x16\n\x0eport_range_max\x18\x03 \x01(\r\x12\x13\n\x0bremote_cidr\x18\x04 \x01(\t\"\xcf\x01\n\rPrivacyPolicy\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\x12\'\n\x03key\x18\x02 \x01(\x0b\x32\x14.edgeproto.PolicyKeyB\x04\xc8\xde\x1f\x00\x12\x46\n\x17outbound_security_rules\x18\x03 \x03(\x0b\x32\x1f.edgeproto.OutboundSecurityRuleB\x04\xc8\xde\x1f\x00:=\xe8\xf3\x18\x01\xf0\xf3\x18\x01\x98\xf4\x18\x01\x80\xf4\x18\x01\x90\xf4\x18\x01\x9a\xf5\x18%name=Key.Name,developer=Key.Developer2\x89\x05\n\x10PrivacyPolicyApi\x12\x9a\x01\n\x13\x43reatePrivacyPolicy\x12\x18.edgeproto.PrivacyPolicy\x1a\x11.edgeproto.Result\"V\x82\xd3\xe4\x93\x02\x1a\"\x15/create/privacypolicy:\x01*\xea\xf4\x18\x32ResourceDeveloperPolicy,ActionManage,Key.Developer\x12\x9a\x01\n\x13\x44\x65letePrivacyPolicy\x12\x18.edgeproto.PrivacyPolicy\x1a\x11.edgeproto.Result\"V\x82\xd3\xe4\x93\x02\x1a\"\x15/delete/privacypolicy:\x01*\xea\xf4\x18\x32ResourceDeveloperPolicy,ActionManage,Key.Developer\x12\x9a\x01\n\x13UpdatePrivacyPolicy\x12\x18.edgeproto.PrivacyPolicy\x1a\x11.edgeproto.Result\"V\x82\xd3\xe4\x93\x02\x1a\"\x15/update/privacypolicy:\x01*\xea\xf4\x18\x32ResourceDeveloperPolicy,ActionManage,Key.Developer\x12\x9d\x01\n\x11ShowPrivacyPolicy\x12\x18.edgeproto.PrivacyPolicy\x1a\x18.edgeproto.PrivacyPolicy\"R\x82\xd3\xe4\x93\x02\x18\"\x13/show/privacypolicy:\x01*\xea\xf4\x18\x30ResourceDeveloperPolicy,ActionView,Key.Developer0\x01\x62\x06proto3')
  ,
  dependencies=[annotations__pb2.DESCRIPTOR,result__pb2.DESCRIPTOR,protogen__pb2.DESCRIPTOR,gogo__pb2.DESCRIPTOR,autoscalepolicy__pb2.DESCRIPTOR,])




_OUTBOUNDSECURITYRULE = _descriptor.Descriptor(
  name='OutboundSecurityRule',
  full_name='edgeproto.OutboundSecurityRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol', full_name='edgeproto.OutboundSecurityRule.protocol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port_range_min', full_name='edgeproto.OutboundSecurityRule.port_range_min', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port_range_max', full_name='edgeproto.OutboundSecurityRule.port_range_max', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remote_cidr', full_name='edgeproto.OutboundSecurityRule.remote_cidr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=227,
)


_PRIVACYPOLICY = _descriptor.Descriptor(
  name='PrivacyPolicy',
  full_name='edgeproto.PrivacyPolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='edgeproto.PrivacyPolicy.fields', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='edgeproto.PrivacyPolicy.key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outbound_security_rules', full_name='edgeproto.PrivacyPolicy.outbound_security_rules', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\310\336\037\000'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\350\363\030\001\360\363\030\001\230\364\030\001\200\364\030\001\220\364\030\001\232\365\030%name=Key.Name,developer=Key.Developer'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=437,
)

_PRIVACYPOLICY.fields_by_name['key'].message_type = autoscalepolicy__pb2._POLICYKEY
_PRIVACYPOLICY.fields_by_name['outbound_security_rules'].message_type = _OUTBOUNDSECURITYRULE
DESCRIPTOR.message_types_by_name['OutboundSecurityRule'] = _OUTBOUNDSECURITYRULE
DESCRIPTOR.message_types_by_name['PrivacyPolicy'] = _PRIVACYPOLICY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OutboundSecurityRule = _reflection.GeneratedProtocolMessageType('OutboundSecurityRule', (_message.Message,), {
  'DESCRIPTOR' : _OUTBOUNDSECURITYRULE,
  '__module__' : 'privacypolicy_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.OutboundSecurityRule)
  })
_sym_db.RegisterMessage(OutboundSecurityRule)

PrivacyPolicy = _reflection.GeneratedProtocolMessageType('PrivacyPolicy', (_message.Message,), {
  'DESCRIPTOR' : _PRIVACYPOLICY,
  '__module__' : 'privacypolicy_pb2'
  # @@protoc_insertion_point(class_scope:edgeproto.PrivacyPolicy)
  })
_sym_db.RegisterMessage(PrivacyPolicy)


_PRIVACYPOLICY.fields_by_name['key']._options = None
_PRIVACYPOLICY.fields_by_name['outbound_security_rules']._options = None
_PRIVACYPOLICY._options = None

_PRIVACYPOLICYAPI = _descriptor.ServiceDescriptor(
  name='PrivacyPolicyApi',
  full_name='edgeproto.PrivacyPolicyApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=440,
  serialized_end=1089,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreatePrivacyPolicy',
    full_name='edgeproto.PrivacyPolicyApi.CreatePrivacyPolicy',
    index=0,
    containing_service=None,
    input_type=_PRIVACYPOLICY,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\032\"\025/create/privacypolicy:\001*\352\364\0302ResourceDeveloperPolicy,ActionManage,Key.Developer'),
  ),
  _descriptor.MethodDescriptor(
    name='DeletePrivacyPolicy',
    full_name='edgeproto.PrivacyPolicyApi.DeletePrivacyPolicy',
    index=1,
    containing_service=None,
    input_type=_PRIVACYPOLICY,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\032\"\025/delete/privacypolicy:\001*\352\364\0302ResourceDeveloperPolicy,ActionManage,Key.Developer'),
  ),
  _descriptor.MethodDescriptor(
    name='UpdatePrivacyPolicy',
    full_name='edgeproto.PrivacyPolicyApi.UpdatePrivacyPolicy',
    index=2,
    containing_service=None,
    input_type=_PRIVACYPOLICY,
    output_type=result__pb2._RESULT,
    serialized_options=_b('\202\323\344\223\002\032\"\025/update/privacypolicy:\001*\352\364\0302ResourceDeveloperPolicy,ActionManage,Key.Developer'),
  ),
  _descriptor.MethodDescriptor(
    name='ShowPrivacyPolicy',
    full_name='edgeproto.PrivacyPolicyApi.ShowPrivacyPolicy',
    index=3,
    containing_service=None,
    input_type=_PRIVACYPOLICY,
    output_type=_PRIVACYPOLICY,
    serialized_options=_b('\202\323\344\223\002\030\"\023/show/privacypolicy:\001*\352\364\0300ResourceDeveloperPolicy,ActionView,Key.Developer'),
  ),
])
_sym_db.RegisterServiceDescriptor(_PRIVACYPOLICYAPI)

DESCRIPTOR.services_by_name['PrivacyPolicyApi'] = _PRIVACYPOLICYAPI

# @@protoc_insertion_point(module_scope)
