# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import restagtable_pb2 as restagtable__pb2
import result_pb2 as result__pb2


class ResTagTableApiStub(object):
  """This API should be admin-only
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateResTagTable = channel.unary_unary(
        '/edgeproto.ResTagTableApi/CreateResTagTable',
        request_serializer=restagtable__pb2.ResTagTable.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.DeleteResTagTable = channel.unary_unary(
        '/edgeproto.ResTagTableApi/DeleteResTagTable',
        request_serializer=restagtable__pb2.ResTagTable.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.UpdateResTagTable = channel.unary_unary(
        '/edgeproto.ResTagTableApi/UpdateResTagTable',
        request_serializer=restagtable__pb2.ResTagTable.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ShowResTagTable = channel.unary_stream(
        '/edgeproto.ResTagTableApi/ShowResTagTable',
        request_serializer=restagtable__pb2.ResTagTable.SerializeToString,
        response_deserializer=restagtable__pb2.ResTagTable.FromString,
        )
    self.AddResTag = channel.unary_unary(
        '/edgeproto.ResTagTableApi/AddResTag',
        request_serializer=restagtable__pb2.ResTagTable.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.RemoveResTag = channel.unary_unary(
        '/edgeproto.ResTagTableApi/RemoveResTag',
        request_serializer=restagtable__pb2.ResTagTable.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.GetResTagTable = channel.unary_unary(
        '/edgeproto.ResTagTableApi/GetResTagTable',
        request_serializer=restagtable__pb2.ResTagTableKey.SerializeToString,
        response_deserializer=restagtable__pb2.ResTagTable.FromString,
        )


class ResTagTableApiServicer(object):
  """This API should be admin-only
  """

  def CreateResTagTable(self, request, context):
    """Create TagTable
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteResTagTable(self, request, context):
    """Delete TagTable
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateResTagTable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowResTagTable(self, request, context):
    """show TagTable
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddResTag(self, request, context):
    """add new tag(s) to TagTable
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveResTag(self, request, context):
    """remove existing tag(s) from TagTable
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetResTagTable(self, request, context):
    """Fetch a copy of the TagTable
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ResTagTableApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateResTagTable': grpc.unary_unary_rpc_method_handler(
          servicer.CreateResTagTable,
          request_deserializer=restagtable__pb2.ResTagTable.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'DeleteResTagTable': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteResTagTable,
          request_deserializer=restagtable__pb2.ResTagTable.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'UpdateResTagTable': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateResTagTable,
          request_deserializer=restagtable__pb2.ResTagTable.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ShowResTagTable': grpc.unary_stream_rpc_method_handler(
          servicer.ShowResTagTable,
          request_deserializer=restagtable__pb2.ResTagTable.FromString,
          response_serializer=restagtable__pb2.ResTagTable.SerializeToString,
      ),
      'AddResTag': grpc.unary_unary_rpc_method_handler(
          servicer.AddResTag,
          request_deserializer=restagtable__pb2.ResTagTable.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'RemoveResTag': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveResTag,
          request_deserializer=restagtable__pb2.ResTagTable.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'GetResTagTable': grpc.unary_unary_rpc_method_handler(
          servicer.GetResTagTable,
          request_deserializer=restagtable__pb2.ResTagTableKey.FromString,
          response_serializer=restagtable__pb2.ResTagTable.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.ResTagTableApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
