# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import result_pb2 as result__pb2
import settings_pb2 as settings__pb2


class SettingsApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UpdateSettings = channel.unary_unary(
        '/edgeproto.SettingsApi/UpdateSettings',
        request_serializer=settings__pb2.Settings.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ResetSettings = channel.unary_unary(
        '/edgeproto.SettingsApi/ResetSettings',
        request_serializer=settings__pb2.Settings.SerializeToString,
        response_deserializer=result__pb2.Result.FromString,
        )
    self.ShowSettings = channel.unary_unary(
        '/edgeproto.SettingsApi/ShowSettings',
        request_serializer=settings__pb2.Settings.SerializeToString,
        response_deserializer=settings__pb2.Settings.FromString,
        )


class SettingsApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UpdateSettings(self, request, context):
    """Update settings
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetSettings(self, request, context):
    """Reset all settings to their defaults
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShowSettings(self, request, context):
    """Show settings
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SettingsApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UpdateSettings': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSettings,
          request_deserializer=settings__pb2.Settings.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ResetSettings': grpc.unary_unary_rpc_method_handler(
          servicer.ResetSettings,
          request_deserializer=settings__pb2.Settings.FromString,
          response_serializer=result__pb2.Result.SerializeToString,
      ),
      'ShowSettings': grpc.unary_unary_rpc_method_handler(
          servicer.ShowSettings,
          request_deserializer=settings__pb2.Settings.FromString,
          response_serializer=settings__pb2.Settings.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'edgeproto.SettingsApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
