# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import annotations_pb2 as annotations__pb2
import protogen_pb2 as protogen__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='version.proto',
  package='edgeproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rversion.proto\x12\tedgeproto\x1a\x11\x61nnotations.proto\x1a\x0eprotogen.proto*\xb4\x05\n\x0bVersionHash\x12)\n%HASH_d41d8cd98f00b204e9800998ecf8427e\x10\x00\x12\x41\n%HASH_b35326df0fcd1550b7c0cf6460c4bca2\x10\x01\x1a\x16\x8a\xf5\x18\x12TestUpgradeExample\x12)\n%HASH_52e6980599cd59bbbd0de8d5f4d53d4b\x10\x02\x12L\n%HASH_00bdcfa956ca4ee42be87abcd8fcaf1c\x10\x03\x1a!\x8a\xf5\x18\x1d\x41\x64\x64\x43lusterInstKeyToAppInstKey\x12\x43\n%HASH_0d2d9c0b07ad989e96fb3b3a44924316\x10\x04\x1a\x18\x8a\xf5\x18\x14LintFixAppInstFields\x12L\n%HASH_2b79f0b6e402045ee5f68d697b9386ae\x10\x05\x1a!\x8a\xf5\x18\x1d\x41\x64\x64\x43lusterInstDeploymentField\x12L\n%HASH_536a69a5e27bf7cf5152d85eba21aa74\x10\x06\x1a!\x8a\xf5\x18\x1d\x41\x64\x64InternalPortsForPrometheus\x12)\n%HASH_caedcdeef911bc00d5dceacf8e55890a\x10\x07\x12)\n%HASH_60febe402fd8f1a1ded0762dbc72a5a8\x10\x08\x12)\n%HASH_d4ca5418a77d22d968ce7a2afc549dfe\x10\t\x12Q\n%HASH_7848d42e3a2eaf36e53bbd3af581b13a\x10\n\x1a&\x8a\xf5\x18\"SetDefaultLoadBalancerMaxPortRange\x1a\t\xf8\xf4\x18\x01\x82\xf5\x18\x01\x31\x62\x06proto3')
  ,
  dependencies=[annotations__pb2.DESCRIPTOR,protogen__pb2.DESCRIPTOR,])

_VERSIONHASH = _descriptor.EnumDescriptor(
  name='VersionHash',
  full_name='edgeproto.VersionHash',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HASH_d41d8cd98f00b204e9800998ecf8427e', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_b35326df0fcd1550b7c0cf6460c4bca2', index=1, number=1,
      serialized_options=_b('\212\365\030\022TestUpgradeExample'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_52e6980599cd59bbbd0de8d5f4d53d4b', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_00bdcfa956ca4ee42be87abcd8fcaf1c', index=3, number=3,
      serialized_options=_b('\212\365\030\035AddClusterInstKeyToAppInstKey'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_0d2d9c0b07ad989e96fb3b3a44924316', index=4, number=4,
      serialized_options=_b('\212\365\030\024LintFixAppInstFields'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_2b79f0b6e402045ee5f68d697b9386ae', index=5, number=5,
      serialized_options=_b('\212\365\030\035AddClusterInstDeploymentField'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_536a69a5e27bf7cf5152d85eba21aa74', index=6, number=6,
      serialized_options=_b('\212\365\030\035AddInternalPortsForPrometheus'),
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_caedcdeef911bc00d5dceacf8e55890a', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_60febe402fd8f1a1ded0762dbc72a5a8', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_d4ca5418a77d22d968ce7a2afc549dfe', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HASH_7848d42e3a2eaf36e53bbd3af581b13a', index=10, number=10,
      serialized_options=_b('\212\365\030\"SetDefaultLoadBalancerMaxPortRange'),
      type=None),
  ],
  containing_type=None,
  serialized_options=_b('\370\364\030\001\202\365\030\0011'),
  serialized_start=64,
  serialized_end=756,
)
_sym_db.RegisterEnumDescriptor(_VERSIONHASH)

VersionHash = enum_type_wrapper.EnumTypeWrapper(_VERSIONHASH)
HASH_d41d8cd98f00b204e9800998ecf8427e = 0
HASH_b35326df0fcd1550b7c0cf6460c4bca2 = 1
HASH_52e6980599cd59bbbd0de8d5f4d53d4b = 2
HASH_00bdcfa956ca4ee42be87abcd8fcaf1c = 3
HASH_0d2d9c0b07ad989e96fb3b3a44924316 = 4
HASH_2b79f0b6e402045ee5f68d697b9386ae = 5
HASH_536a69a5e27bf7cf5152d85eba21aa74 = 6
HASH_caedcdeef911bc00d5dceacf8e55890a = 7
HASH_60febe402fd8f1a1ded0762dbc72a5a8 = 8
HASH_d4ca5418a77d22d968ce7a2afc549dfe = 9
HASH_7848d42e3a2eaf36e53bbd3af581b13a = 10


DESCRIPTOR.enum_types_by_name['VersionHash'] = _VERSIONHASH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_VERSIONHASH._options = None
_VERSIONHASH.values_by_name["HASH_b35326df0fcd1550b7c0cf6460c4bca2"]._options = None
_VERSIONHASH.values_by_name["HASH_00bdcfa956ca4ee42be87abcd8fcaf1c"]._options = None
_VERSIONHASH.values_by_name["HASH_0d2d9c0b07ad989e96fb3b3a44924316"]._options = None
_VERSIONHASH.values_by_name["HASH_2b79f0b6e402045ee5f68d697b9386ae"]._options = None
_VERSIONHASH.values_by_name["HASH_536a69a5e27bf7cf5152d85eba21aa74"]._options = None
_VERSIONHASH.values_by_name["HASH_7848d42e3a2eaf36e53bbd3af581b13a"]._options = None
# @@protoc_insertion_point(module_scope)
