from selenium.webdriver.common.by import By
import logging

class BasePageLocators(object):
    #alert_box = (By.CSS_SELECTOR, 'div.s-alert-box-inner')
    alert_box = (By.XPATH, '//div[@class="MuiAlert-message"]')
    dialog_box = (By.XPATH, '//div[@class="MuiDialog-root"]')
    text_box = (By.XPATH, '//div[@class="MuiDialog-container MuiDialog-scrollPaper"]//p') 
    page_number = (By.XPATH, '//p[@class="MuiTypography-root MuiTablePagination-caption MuiTypography-body2 MuiTypography-colorInherit"][2]')

class LoginPageLocators(object):
    username_field = (By.NAME, 'username')
    password_field = (By.NAME, 'password')
    login_button = (By.XPATH, '//button[text()="Log In"]')
    login_switch_button = (By.XPATH, '//div/a[text()="Login"]')
    register_switch_button = (By.XPATH, '//div/a[text()="Register"]')
    #signup_switch_button = (By.XPATH, '//button/span[text()="Create an account"]')
    # forgot_password_link = (By.CSS_SELECTOR, 'div.login-text')
    #login_validation = (By.CSS_SELECTOR, 'div.loginValidation')
    login_validation = (By.XPATH, '//div[@class="loginValidation"]')
    forgot_password_link= (By.XPATH, '//div[@class="row"]//div[text()="Forgot Password?"]')
    

class MainPageLocators(object):
    compute_button = (By.XPATH, '//button[text()="MobiledgeX Compute"]')
    monitoring_button = (By.XPATH, '//button[text()="MobiledgeX Monitoring"]')
    #avatar = (By.XPATH, '//img[@src="/assets/avatar/avatar_default.svg"]')
    #avatar = (By.XPATH, '//*[@class="MuiSvgIcon-root MuiSvgIcon-fontSizeLarge"]')
    avatar = (By.XPATH, '//*[@class="MuiSvgIcon-root"]')
    username = (By.XPATH, '//*[@class="navbar_right"]//span')
    alert_box = (By.CSS_SELECTOR, 'div.s-alert-box-inner')
    logout_button = (By.XPATH, '//button[@class="ui button"][2]/div[2]')

class ComputePageLocators(object):
    #brand_class = (By.CSS_SELECTOR, 'div.content.brand')
    brand = (By.XPATH, '//img[@src="/assets/brand/logo_mex.svg"]')
    icons_class = (By.CSS_SELECTOR, 'i.material-icons.md-24.md-dark')
    #avatar = (By.XPATH, '//img[@src="/assets/avatar/avatar_default.svg"]')
    #avatar = (By.XPATH, '//div[@class="ten wide column navbar_right"]/div[6]')
    avatar = (By.XPATH, '//div[contains(@class, "makeStyles-sectionDesktop")]/div[5]/button[1]')
    avatar1 = (By.XPATH, '//div[contains(@class, "makeStyles-sectionDesktop")]/div[3]/button[1]')
    username_div = (By.XPATH, '//*[@class="ui avatar image"]/..')
    support = (By.XPATH, '//div[contains(text(),"Support")]')

    #table_title = (By.CSS_SELECTOR, 'div.column.title_align')
    #table_title = (By.XPATH, '//label[@class="content_title_label"]')
    table_title = (By.XPATH, '//h4[contains( @class ,"MuiTypography-root")]')
    #table_new_button = (By.XPATH, '//button[@class="ui teal button" and contains(text(), "New")]')
    table_new_button = (By.XPATH, '//button[@aria-label="new"]')
    table_add_button = (By.XPATH, '//button[contains(.,"add")]')
    table_help_button = (By.CSS_SELECTOR, 'i.question.circle.outline.small.icon')
    #table_region_label = (By.XPATH, '//div[@class="row"]/label[text()="Region"]')
    table_region_label = (By.XPATH, '//div/strong[contains(text(), "Region:")]')
    menu_labels = "//div[@class='select-menu-label']/strong"
    #table_region_pulldown = (By.XPATH, '//div[@class="row"]/div[@class="ui dropdown selection"]')
    #table_region_pulldown = (By.XPATH, '//div[@class="ui dropdown"]')
    table_region_pulldown = (By.XPATH, '//div[@aria-controls="chart"]')
    #table_region_pulldown_option_all = (By.XPATH, '//div[@class="row"]/div[@class="ui active visible dropdown selection"]//div[@role="option"]/span[text()="ALL"]')
    #table_region_pulldown_option_us = (By.XPATH, '//div[@class="row"]/div[@class="ui active visible dropdown selection"]//div[@role="option"]/span[text()="US"]')
    #table_region_pulldown_option_eu = (By.XPATH, '//div[@class="row"]/div[@class="ui active visible dropdown selection"]//div[@role="option"]/span[text()="EU"]')
    table_region_pulldown_option_all = (By.XPATH, '//div[1]//span[text()="ALL"]')
    table_region_pulldown_option_us = (By.XPATH, '//div[3]//span[text()="US"]')
    table_region_pulldown_option_eu = (By.XPATH, '//div[2]//span[text()="EU"]')

    #table_class = (By.CSS_SELECTOR, 'div.grid_table')
    table_class = (By.CSS_SELECTOR, 'table.viewListTable')
    #table_data = (By.CSS_SELECTOR, 'tbody.tbBodyList')
    table_data = (By.XPATH, '//div[@id="table-container"]')
    #table_delete = (By.CSS_SELECTOR, 'i.trash')
    table_action = (By.XPATH, '//span[contains(.,"list")]/parent::button')
    table_delete = (By.XPATH, './/li[text()="Delete"]')
    table_update = (By.XPATH, './/li[text()="Update"]')
    new_icon = (By.CSS_SELECTOR, 'div.userNewMark.mextester01')
   # organization_details = (By.XPATH, '//[@class="left aligned"]')
    show_manifest = (By.XPATH, './/li[text()="Show Manifest"]')
    accounts_button = (By.XPATH, '//*[@class="MuiListItemText-root"]//span[text()="Accounts"]')
    organizations_button = (By.XPATH, '//*[@class="MuiListItemText-root"]//span[text()="Organizations"]')
    users_button = (By.XPATH, '//*[@class="MuiListItemText-root"]//span[text()="Users & Roles"]')
    cloudlets_button = (By.XPATH, '//*[@class="MuiListItemText-root"]//span[text()="Cloudlets"]')
    flavors_button = (By.XPATH, '//*[@class="MuiListItemText-root"]/span[text()="Flavors"]')
    cluster_instances_button = (By.XPATH, '//*[@class="MuiListItemText-root"]//span[text()="Cluster Instances"]')
    apps_button = (By.XPATH, '//*[@class="MuiListItemText-root"]//span[text()="Apps"]')
    app_instances_button = (By.XPATH, '//*[@class="MuiListItemText-root"]//span[text()="App Instances"]')
    #refresh_button = (By.XPATH, '//i[@class="material-icons md-24 md-dark " and text()="refresh"]')
    #refresh_button = (By.XPATH, '//div[@class="ten wide column navbar_right"]/div[1]')
    refresh_button =  (By.XPATH, '//button[contains(.,"refresh")]')
    #refresh_button = (By.XPATH, '//div[@class="ten wide column navbar_right"]/div[0]/svg')
    #public_button = (By.XPATH, '//i[@class="material-icons md-24 md-dark " and text()="public"]')
    #public_button = (By.XPATH, '//div[@class="ten wide column navbar_right"]/div[2]')
    public_button = (By.XPATH, '//div[contains(@class, "makeStyles-sectionDesktop")]/button[2]')
    help_button = (By.XPATH, '(//div[contains(@class, "makeStyles-sectionDesktop")]//*[local-name() = "svg"])[3]')
    help_button1 = (By.XPATH, '//div[contains(@class, "makeStyles-sectionDesktop")]/div[2]/button[1]')
    #help_button = (By.XPATH, '//svg[contains(@class, "makeStyles-sectionDesktop")]/button[3]')
    #help_button = (By.XPATH, '//div[@class="ten wide column navbar_right"]/div[4]')
    trash_button = (By.XPATH, './/i[@class="trash alternate icon"]/..')
    #add_user_button = (By.XPATH, '//button[@class="ui teal button" and contains(text(), "Add User")]')
    add_user_button = (By.XPATH, '//button[text()="Add User"]')
    i_icon = (By.CSS_SELECTOR, 'a.introjs-button.introjs-skipbutton')
    next_page_button = '//div[@class="MuiTablePagination-actions"]/button[@type="button" and @title="Next page"]'
    rows_per_page = (By.XPATH, '//div[@class="MuiInputBase-root MuiTablePagination-input MuiTablePagination-selectRoot"]//div[@role="button"]')
    rows_per_page_75 = (By.XPATH, '//li[@data-value="75"]')
   
    select_developer_org = (By.XPATH, '//div[@class="MuiCardHeader-action"]/button[@aria-label="developer"]') 
    select_operator_org = (By.XPATH, '//div[@class="MuiCardHeader-action"]/button[@aria-label="operator"]')
    manage_button = (By.XPATH, '//div[@class="MuiTableContainer-root"]//span[@class="MuiButton-label"]/label[text()="Manage"]')
    #close_button = (By.XPATH, '//div[@class="MuiDialog-root"]//button[@type="button"]/span[@class="MuiIconButton-label"]/svg[@class="MuiSvgIcon-root"]')
    close_button = (By.XPATH, '//div[@class="MuiDialog-root"]//button[@aria-label="delete"]')
    search_icon = (By.CSS_SELECTOR, 'div.MuiInputAdornment-root')
    search_box = (By.XPATH, '//input[@placeholder="Search"]')
    details_row = (By.XPATH, '//table/tbody/tr')
    policies_button = (By.XPATH, '//div[@role="button"]/div[1][@title="Policies"]')
    autoscalepolicy_option = (By.XPATH, './/div[@class="MuiList-root"]/div[3]')
    trustpolicy_option = (By.XPATH, './/div[@class="MuiList-root"]/div[2]')
    searchbutton = (By.XPATH, '//div[contains(@class,"MuiInputBase-root MuiInput-root makeStyles-inputRoot")]')
    searchInput = (By.XPATH, '//div[contains(@class,"MuiInputBase-root MuiInput-root makeStyles-inputRoot")]//input')

class FlavorsPageLocators(object):
    flavors_table_header_region = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Region")]')
    flavors_table_header_flavorname = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Flavor Name")]')
    flavors_table_header_ram = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "RAM Size(MB)")]')
    flavors_table_header_vcpus = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Number of vCPUs")]')
    flavors_table_header_disk = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Disk Space(GB)")]')
    flavors_table_header_gpu = (By.XPATH, '//table/thead//strong[text()="Number of GPUs"]')
    flavors_table_header_edit = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Actions")]')
    flavors_table_button_edit = (By.XPATH, '//table/tbody/tr/td/button[text()="Actions"]')
    table_delete = (By.XPATH, './/i[@class="trash alternate icon"]')
    #close_button =  (By.XPATH, '//button[text()="Close"]')
    close_button = (By.XPATH, '//button[@class="MuiButtonBase-root MuiIconButton-root" and @aria-label="refresh"]')
    rows_per_page = (By.XPATH, '//div[@class="MuiInputBase-root MuiTablePagination-input MuiTablePagination-selectRoot"]//div[@role="button"]')
    rows_per_page_75 = (By.XPATH, '//li[@data-value="75"]')
    next_page_button = (By.XPATH, '//div[@class="MuiTablePagination-actions"]/button[@type="button" and @title="Next page"]')
    previous_page_button = (By.XPATH, '//div[@class="MuiTablePagination-actions"]/button[@type="button" and @title="Previous page"]')
    details_row = (By.XPATH, '//table[@class="MuiTable-root MuiTable-stickyHeader"]/tbody/tr')
    flavors_searchbutton = (By.XPATH, '//div[contains(@class,"MuiInputBase-root MuiInput-root makeStyles-inputRoot")]')
    flavors_searchInput = (By.XPATH, '//div[contains(@class,"MuiInputBase-root MuiInput-root makeStyles-inputRoot")]//input')
    flavors_table_gpu_icon = (By.XPATH, '//td/img[@src="/assets/icons/gpu_green.svg"]')

class CloudletsPageLocators(object):
    cloudlets_table_header_region = (By.XPATH, '//table/thead//strong[text()="Region"]')
    cloudlets_table_header_cloudletname = (By.XPATH, '//table/thead//strong[text()="Cloudlet"]')
    cloudlets_table_header_operator = (By.XPATH, '//table/thead//strong[text()="Operator"]')
    cloudlets_table_header_cloudletlocation = (By.XPATH, '//table/thead/tr/th/span[text()="Cloudlet Location"]')
    cloudlets_table_header_status = (By.XPATH, '//table/thead//strong[text()="Cloudlet Status"]')
    cloudlets_table_header_progress = (By.XPATH, '//table/thead//strong[text()="Progress"]')
    cloudlets_table_header_edit = (By.XPATH, '//table/thead//strong[text()="Actions"]')
    cloudlets_map_icon = (By.CSS_SELECTOR, 'text.marker_value')
    cloudlets_expand_icon = (By.CSS_SELECTOR, 'i.expand.icon')
    cloudlets_zoom_out_icon = (By.CSS_SELECTOR, 'i.minus.square.outline.icon')
    cloudlets_zoom_in_icon = (By.CSS_SELECTOR, 'i.plus.square.outline.icon')
    advancedsettings_button = (By.XPATH, '//div[@class="ui grid"]//h3[text()="Advanced Settings"]/button[@type="button"]')
    maintenance_state_pulldown = (By.XPATH, '//div[@class="eleven wide column"]/div[@id="maintenanceState"]//i[@class="dropdown icon"]')
    maintenance_state_option1 = (By.XPATH, '//div[@role="listbox"]/div//span[text()="Maintenance Start"]')
    maintenance_state_option2 = (By.XPATH, '//div[@role="listbox"]/div//span[text()="Maintenance Start No Failover"]') 
    maintenance_state_normal_operation = (By.XPATH, '//div[@role="listbox"]/div//span[text()="Normal Operation"]')
    maintenance_state_list = (By.XPATH, '//div[@class="eleven wide column"]/div[@id="maintenanceState"]/input[@type="text"]')
    update_button = (By.XPATH, '//div[@class="inline fields"]/button[1]//span[@class="MuiButton-label" and text()="Update"]')
    select_no = (By.XPATH, './/button[1]/span[text()="NO"]')
    select_yes = (By.XPATH, './/button[2]/span[text()="YES"]')
    trustpolicy_dropdown_clear = (By.XPATH, '//div[@id="trustPolicyName"]//i[@class="dropdown icon clear"]')
    cloudlets_searchbutton = (By.XPATH, '//div[contains(@class,"MuiInputBase-root MuiInput-root makeStyles-inputRoot")]')
    cloudlets_searchInput = (By.XPATH, '//div[contains(@class,"MuiInputBase-root MuiInput-root makeStyles-inputRoot")]//input')

class ClusterInstancesPageLocators(object):
    cluster_instances_table_header_region = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Region")]')
    cluster_instances_table_header_clustername = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Cluster")]')
    cluster_instances_table_header_orgname = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Organization")]')
    cluster_instances_table_header_operator = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Cloudlet [Operator]")]')
    cluster_instances_table_header_cloudlet = (By.XPATH, '//table/thead/tr/th[text()="Cloudlet"]')
    cluster_instances_table_header_flavor = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Flavor")]')
    cluster_instances_table_header_deployment = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Deployment")]')
    cluster_instances_table_header_ipaccess = (By.XPATH, '//table/thead/tr/th[text()="IP Access"]')
    cluster_instances_table_header_location = (By.XPATH, '//table/thead/tr/th[text()="Cloudlet Location"]')
    cluster_instances_table_header_state = (By.XPATH, '//table/thead/tr/th[text()="State"]')
    cluster_instances_table_header_progress = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Progress")]')
    cluster_instances_table_header_actions = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Actions")]')
    table_delete = (By.XPATH, './/i[@class="trash alternate icon"]')
    table_action = (By.XPATH, './/button[@aria-label="Action"]')
    cluster_map_icon = (By.CSS_SELECTOR, 'text.marker_value')
    cluster_expand_icon = (By.CSS_SELECTOR, 'i.expand.icon')
    cluster_zoom_out_icon = (By.CSS_SELECTOR, 'i.minus.square.outline.icon')
    cluster_zoom_in_icon = (By.CSS_SELECTOR, 'i.plus.square.outline.icon')

    clusterinst_region = (By.XPATH, '//div[text()="Region"]/sup[text()=" *"]')
    clusterinst_region_input = (By.XPATH, '//div[@id="region"]')
    clusterinst_clustername = (By.XPATH, '//div[text()="Cluster Name"]/sup[text()=" *"]')
    clusterinst_clustername_input = (By.XPATH, '//input[@placeholder="Enter Cluster Inst Name"]')
    clusterinst_developername = (By.XPATH, '//div[text()="Organization"]/sup[text()=" *"]')
    clusterinst_developername_pulldown = (By.XPATH, '//div[@role="combobox"]//div[text()="Select Developer"]')
    clusterinst_developername_pulldownbox = (By.XPATH, '//div[@id="organizationName"]')
    clusterinst_operatorname = (By.XPATH, '//div[text()="Operator"]/sup[text()=" *"]')
    clusterinst_operatorname_pulldown = (By.XPATH, '//div[@role="combobox"]//div[text()="Select Operator"]')
    clusterinst_operatorname_pulldownbox = (By.XPATH, '//div[@id="operatorName"]')
    clusterinst_cloudletname = (By.XPATH, '//div[text()="Cloudlet"]/sup[text()=" *"]')
    clusterinst_cloudletname_pulldown = (By.XPATH, '//div[@id="cloudletName"]//div[text()="Select Cloudlet"]')
    clusterinst_cloudletname_pulldown2 = (By.XPATH, '//div[@id="cloudletName"]')
    clusterinst_deploymenttype = (By.XPATH, '//div[text()="Deployment Type"]/sup[text()=" *"]')
    clusterinst_deploymenttype_pulldown = (By.XPATH, '//div[@role="combobox"]//div[text()="Select Deployment Type"]')
    clusterinst_deploymenttype_pulldownbox = (By.XPATH, '//div[@id="deployment"]')
    clusterinst_ipaccess = (By.XPATH, '//div[text()="IP Access"]')
    clusterinst_ipaccess_pulldown = (By.XPATH, '//div[@role="combobox"]//div[text()="Select IP Access"]')
    clusterinst_ipaccess_pulldownbox = (By.XPATH, '//div[@id="ipAccess"]')
    clusterinst_flavor = (By.XPATH, '//div[text()="Flavor"]/sup[text()=" *"]')
    clusterinst_flavor_pulldown = (By.XPATH, '//div[@id="flavorName"]//div[text()="Select Flavor"]')
    clusterinst_flavor_pulldownbox = (By.XPATH, '//div[@id="flavorName"]')
    clusterinst_flavor_input = (By.XPATH, '//div[@id="flavorName"]/following-sibling::div//input')
    clusterinst_network = (By.XPATH, '//div[text()="Network"]')
    clusterinst_network_pulldown = (By.ID, 'networks')
    clusterinst_autoscalepolicy = (By.XPATH, '//div[text()="Auto Scale Policy"]')
    clusterinst_autoscalepolicy_pulldown = (By.XPATH, '//div[@role="combobox"]//div[text()="Select Auto Scale Policy"]')
    clusterinst_details_clustername = (By.XPATH, '//td[text()="Cluster"]')
    clusterinst_details_developername = (By.XPATH, '//td[text()="Organization"]')
    clusterinst_details_operatorname = (By.XPATH, '//td[text()="Operator"]')
    clusterinst_details_cloudletname = (By.XPATH, '//td[text()="Cloudlet"]')
    clusterinst_details_flavorname = (By.XPATH, '//td[text()="Flavor"]')
    clusterinst_details_deploymenttype = (By.XPATH, '//td[text()="Deployment"]')

class PrivacyPolicyPageLocators(object):
    region_label = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Region"]/sup[text()=" *"]')
    region_input = (By.XPATH, '//div[@id="region"]/div[text()="Select Region"]')
    orgname_pulldown = (By.XPATH, '//div[@id="organizationName"]')
    trustpolicy_name_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Trust Policy Name"]')
    trustpolicy_name_label = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Trust Policy Name"]/sup[text()=" *"]')
    orgname_label = (By.XPATH, '//div[@class="four wide column detail_item"]//div[text()="Organization"]/sup[text()=" *"]')
    orgname_input = (By.XPATH, '//div[@id="organizationName"]/div[text()="Select Organization"]')
    security_rules_header = (By.XPATH, '//div[@class="fifteen wide column detail_item"]/h3[text()="Outbound Security Rules"]')
    protocol_label = (By.XPATH, '//div[@class="three wide column"]/label[text()="Protocol" and text()=" *"]')
    port_range_min_label = (By.XPATH, '//div[@class="three wide column"]/label[text()="Port Range Min" and text()=" *"]')
    port_range_max_label = (By.XPATH, '//div[@class="three wide column"]/label[text()="Port Range Max" and text()=" *"]')
    remote_cidr_label = (By.XPATH, '//div[@class="three wide column"]/label[text()="Remote CIDR" and text()=" *"]')
    protocol_pulldown = (By.XPATH, '//div[@id="protocol"]/input[@type="text"]')
    protocol_option = (By.XPATH, '//div[@role="listbox"]/div')
    port_range_min_input = (By.XPATH, '//div[@id="outboundSecurityRuleMulti"]/div[2]//input[@type="number"]')
    port_range_max_input = (By.XPATH, '//div[@id="outboundSecurityRuleMulti"]/div[3]//input[@type="number"]')
    remote_cidr_input = (By.XPATH, '//div[@id="outboundSecurityRuleMulti"]/div[4]//input[@type="text"]')
    remote_cidr_icmp_input = (By.XPATH, '//div[@id="outboundSecurityRuleMulti"]/div[2]//input[@type="text"]')
    create_button = (By.XPATH, '//form[@class="ui form"]//div[@class="inline fields"]/button[1]//span[@class="MuiButton-label" and text()="Create Policy"]')
    cancel_button = (By.XPATH, '//form[@class="ui form"]//div[@class="inline fields"]/button[2]//span[@class="MuiButton-label" and text()="Cancel"]')
    table_action = (By.XPATH, './/button[@aria-label="Action"]')
    full_isolation_button = (By.XPATH, '//div[@class="three column row formRow-4"]//span[@class="MuiIconButton-label"]')
    security_rules_button = (By.XPATH, '//div[@class="ui grid"]//h3[text()="Outbound Security Rules"]/button[@type="button"]')
    delete_rules_button = (By.XPATH, '//div[@id="outboundSecurityRuleMulti"]/div[3]/button/span[@class="MuiIconButton-label"]')
    update_button = (By.XPATH, '//form[@class="ui form"]//div[@class="inline fields"]/button[1]//span[@class="MuiButton-label" and text()="Update Policy"]')

class AutoScalePolicyPageLocators(object):
    orgname_pulldown = (By.XPATH, '//div[@id="organizationName"]')
    autoscalepolicy_name_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Auto Scale Policy Name"]')
    minnodes_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Minimum Nodes"]')
    maxnodes_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Maximum Nodes"]')
    scaledown_input = (By.XPATH, '//div[@class="ui right labeled input"]/input[@placeholder="Enter Scale Down CPU Threshold"]')
    scaleup_input = (By.XPATH, '//div[@class="ui right labeled input"]/input[@placeholder="Enter Scale Up CPU Threshold"]')
    triggertime_input = (By.XPATH, '//div[@class="ui right labeled input"]/input[@placeholder="Enter Trigger Time In Seconds"]')
    create_button = (By.XPATH, '//form[@class="ui form"]//div[@class="inline fields"]/button[1]//span[@class="MuiButton-label" and text()="Create Policy"]')
    region_label = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Region"]/sup[text()=" *"]')
    region_input = (By.XPATH, '//div[@id="region"]/div[text()="Select Region"]')
    orgname_label = (By.XPATH, '//div[@class="four wide column detail_item"]//div[text()="Organization"]/sup[text()=" *"]') 
    orgname_input = (By.XPATH, '//div[@id="organizationName"]/div[text()="Select Organization"]')
    autoscalepolicy_name_label = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Auto Scale Policy Name"]/sup[text()=" *"]')
    minnodes_label = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Minimum Nodes"]/sup[text()=" *"]')
    maxnodes_label = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Maximum Nodes"]/sup[text()=" *"]')
    scaledown_label = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Scale Down CPU Threshold"]/sup[text()=" *"]')
    scaleup_label = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Scale Up CPU Threshold"]/sup[text()=" *"]')
    triggertime_label = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Trigger Time"]/sup[text()=" *"]')
    table_action = (By.XPATH, './/button[@aria-label="Action"]')
    update_button = (By.XPATH, '//form[@class="ui form"]//div[@class="inline fields"]/button[1]//span[@class="MuiButton-label" and text()="Update Policy"]')

class AppsPageLocators(object):
    apps_table_header_region = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Region")]')
    apps_table_header_appname = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and (text()="App [Version]")]')
    apps_table_header_orgname = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and (text()="Organization")]')
    apps_table_header_deploymenttype = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and (text()="Deployment")]')
    apps_table_header_action = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Actions")]')
    apps_table_header_defaultflavor = (By.XPATH, '//table/thead/tr/th[text()="Default Flavor"]')
    apps_table_header_ports = (By.XPATH, '//table/thead/tr/th[text()="Ports"]')
    apps_table_header_edit = (By.XPATH, '//table/thead/tr/th[text()="Actions"]')
    table_delete = (By.XPATH, './/i[@class="trash alternate icon"]')
    apps_page_searchbutton = (By.XPATH, '//div[contains(@class,"MuiInputBase-root MuiInput-root makeStyles-inputRoot")]')
    apps_page_searchInput = (By.XPATH, '//div[contains(@class,"MuiInputBase-root MuiInput-root makeStyles-inputRoot")]//input')
    app_launch = (By.XPATH, './/button[text()="Launch"]')
    apps_region = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Region"]/sup[text()=" *"]')
    apps_region_input = (By.XPATH, '//div[@id="region"]/div[text()="Select Region"]')
    apps_region_pulldown = (By.XPATH, '//div[@id="region"]')
    apps_region_pulldown_options = (By.XPATH, '//div[@id="region"]')
    apps_region_input2 = (By.XPATH, './/div[@class="visible menu transition"]/div')
    apps_orgname = (By.XPATH, '//div[@class="four wide column detail_item"]//div[text()="Organization"]/sup[text()=" *"]')
    apps_orgname_pulldown = (By.XPATH, '//div[@id="organizationName"]')
    apps_appname = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="App Name"]/sup[text()=" *"]')
    apps_appname_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter App Name"]')
    apps_appversion = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="App Version"]/sup[text()=" *"]')
    apps_appversion_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter App Version"]')
    apps_deploymenttype = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Deployment Type"]/sup[text()=" *"]')
    apps_deploymenttype_pulldown = (By.XPATH, '//div[@id="deployment"]')
    apps_deploymenttype_option = (By.XPATH, '//div[@role="listbox"]/div')
    apps_accesstype = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Access Type"]/sup[text()=" *"]')
    apps_accesstype_pulldown = (By.XPATH, '//div[@class="eleven wide column"]/div[@id="accessType"]//i[@class="dropdown icon"]')
    apps_imagetype = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Image Type"]/sup[text()=" *"]')
    apps_imagetype_disabled = (By.XPATH, '//div[@class="ui disabled input"]/input[@placeholder="Select Image Type"]')
    apps_imagepath = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Image Path"]')
    apps_imagepath_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Image Path"]')
    apps_authpublickey = (By.XPATH, '//*[@class="ui two column grid"]/div[8]')
    apps_authpublickey_input = (By.XPATH, '//*[@class="eleven wide column"]/div[@class="field"]')
    apps_flavor = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Default Flavor"]/sup[text()=" *"]')
    apps_flavor_pulldown = (By.XPATH, '//div[@class="eleven wide column"]//div[@id="flavorName"]//div[text()="Select Flavor"]')
    apps_manifest = (By.XPATH, '//*[@class="four wide column detail_item"]/div[text()="Deployment Manifest"]')
    apps_manifest_input = (By.XPATH, '//div[@class="eleven wide column"]//textarea[@id="deploymentManifest"]')
    apps_ports = (By.XPATH, '//div[@id="ports"]//p[text()="Port"]')
    apps_ports_input = (By.XPATH, '//div[@id="ports"]//p[text()="Port"]')
    apps_ports_button = (By.XPATH, '//button[@title="Add Port Mappings"]')
    apps_fqdn = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Official FQDN"]')
    apps_fqdn_input = (By.NAME, 'DefaultFQDN')
    apps_packagename = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Package Name"]')
    apps_packagename_input = (By.NAME, 'PackageName')
    apps_scalewithcluster = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Scale With Cluster"]')
    apps_scalewithcluster_input = (By.XPATH, '//*[@class="ui fitted toggle checkbox"]')
    apps_command = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Command"]')
    apps_command_input = (By.NAME, 'Command')
    apps_deploymentmanifest = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Deployment Manifest"]')
    apps_deploymentmanifest_input = (By.NAME, 'DeploymentMF')
    apps_details_region = (By.XPATH, '//td/strong[text()="Region"]')
    apps_details_developername = (By.XPATH, '//td/strong[text()="Organization"]')
    apps_details_appname = (By.XPATH, '//td/strong[text()="App"]')
    apps_details_version = (By.XPATH, '//td/strong[text()="Version"]')
    apps_details_deploymenttype = (By.XPATH, '//td/strong[text()="Deployment"]')
    apps_details_imagetype = (By.XPATH, '//td/strong[text()="Image Type"]')
    apps_details_imagepath = (By.XPATH, '//td/strong[text()="Image Path"]')
    apps_details_flavors = (By.XPATH, '//td/strong[text()="Default Flavor"]')
    apps_advancedsettings_button = (By.XPATH, '//h3[text()="Advanced Settings"]/button[@type="button"]')
    select_region = (By.XPATH, './/button[@class="mex_select_tree_group"]')
    select_flavor = (By.XPATH, '//button[text()="automation_api_flavor"]')
    create_button = (By.XPATH, '//form[@class="ui form"]//span[text()="Create"]/ancestor::button')
    update_button = (By.XPATH, '//div[@id="submitButtonGroup"]//span[text()="Update"]')
    add_ports_button = (By.XPATH, '//h3[contains(.,"Ports")]/button')
    apps_portnumber_input = (By.XPATH, '//div[@id="ports"]//div[@class="ui input"]/input[@type="number"]')
    apps_protocol_pulldown = (By.XPATH, '//div[@id="protocol"]//div[text()="Select"]')
    apps_protocol_option = (By.XPATH, '//div[@role="listbox"]/div')
    next_page_button = (By.XPATH, '//div[@class="MuiTablePagination-actions"]/button[@type="button" and @title="Next page"]')
    previous_page_button = (By.XPATH, '//div[@class="MuiTablePagination-actions"]/button[@type="button" and @title="Previous page"]')
    toggle_button = (By.XPATH, '//div[@class="three column row formRow-23"]//span[@class="MuiIconButton-label"]')
    updateapp_toggle_button = (By.XPATH, '//div[@class="three column row formRow-23"]//span[@class="MuiIconButton-label"]')
    apps_publickey_input = (By.XPATH, '//div[@class="eleven wide column"]/textarea[@id="authPublicKey"]')
    apps_officialfqdn_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Official FQDN"]')
    configs_button = (By.XPATH, '//h3[contains(.,"Configs")]/button')
    configs_input = (By.XPATH, '//div[@id="configmulti"]//textarea[@id="config"]')
    configs_kind_pulldown = (By.XPATH, '//div[@id="kind"]//i[@class="dropdown icon"]')
    configs_kind_input = (By.XPATH, './/div[@class="visible menu transition"]/div/span[text()="Environment Variables Yaml"]')
    configs_kind_input_helm = (By.XPATH, './/div[@class="visible menu transition"]/div/span[text()="Helm Customization Yaml"]')
    apps_androidpackage_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Package Name"]')
    apps_tls_button = (By.XPATH, '//div[@class="two wide column"]/div/span[@class="MuiSwitch-root"]//span[@class="MuiIconButton-label"]')
    apps_access_type_input = (By.XPATH, '//div[@id="accessType"]/input[@type="text"]')
    apps_access_type_option = (By.XPATH, './/div[@role="listbox"]/div[@role="option"]')
    apps_skiphc_button = (By.XPATH, '//div[@class="three wide column"]/div/span[@class="MuiSwitch-root"]//span[@class="MuiIconButton-label"]')
    flavor_input = (By.XPATH, '//div[@class="tree_popper"]//input[@type="text"]')
    close_button = (By.XPATH, '//button[@class="MuiButtonBase-root MuiIconButton-root" and @aria-label="refresh"]')
    apps_details_configs = (By.XPATH, '//td[text()="Configs"]')
    apps_details_deployment_manifest = (By.XPATH, '//td[text()="Deployment Manifest"]')
    trusted_app_toggle_button = (By.XPATH, '//div[contains(text(),"Trusted")]/ancestor::div[contains(@class,"formRow-13")]//span[@class="MuiIconButton-label"]/input[contains(@class,"MuiSwitch-input")]')
    create_instance = (By.XPATH, './/li[text()="Create Instance"]')
    outbound_connections_button = (By.XPATH, '//h3[contains(.,"Required Outbound Connections")]/button')
    outbound_connections_protocol_pulldown = (By.XPATH, '//div[@id="ocProtocol"]//div[text()="Select"]')
    outbound_connections_portrangemin_input = (By.XPATH, '(//div[@id="requiredOutboundConnectionmulti"]//div[@class="ui input"]/input)[1]')
    outbound_connections_portrangemax_input = (By.XPATH, '(//div[@id="requiredOutboundConnectionmulti"]//div[@class="ui input"]/input)[2]')
    outbound_connections_remoteip_input = (By.XPATH, '(//div[@id="requiredOutboundConnectionmulti"]//div[@class="ui input"]/input)[3]')

class AppInstancesPageLocators(object):
    app_instances_table_header_region = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Region")]')
    app_instances_table_header_appname = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "App [Version]")]')
    app_instances_table_header_orgname = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Organization")]')
    app_instances_table_header_version = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Version")]')
    app_instances_table_header_operator_cloudlet = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Cloudlet [Operator]")]')
    app_instances_table_header_cloudlet = (By.XPATH, '//table/thead/tr/th/span[@role="button"]/div[text()="Cloudlet"]')
    app_instances_table_header_cluster = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Cluster Instance")]')
    #app_instances_table_header_location = (By.XPATH, '//table/thead/tr/th[text()="Cloudlet Location"]')
    app_instances_table_header_health_status = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Health Status")]')
    app_instances_table_header_progress = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Progress")]')
    app_instances_table_header_actions = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Actions")]')
    app_instances_table_header_deployment = (By.XPATH, '//div[@id="mex-data-grid"]//span[contains(@class,"textHeader") and contains(text(), "Deployment")]')
    table_delete = (By.XPATH, './/i[@class="trash alternate icon"]')
    app_launch = (By.XPATH, './/button[text()="Launch"]')
    appinst_region = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Region"]/sup[text()=" *"]')
    appinst_region_pulldown = (By.XPATH, '//div[@id="region"]')
    appinst_developername = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Organization"]')
    appinst_developername_pulldown =  (By.XPATH, '//div[@id="organizationName"]')
    appinst_appname = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="App"]/sup[text()=" *"]')
    appinst_appname_pulldown = (By.XPATH, '//div[@id="appName"]')
    appinst_appversion = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="App Version"]/sup[text()=" *"]')
    appinst_appversion_pulldown = (By.XPATH, '//div[@id="version"]')
    appinst_operator = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Operator"]/sup[text()=" *"]')
    appinst_operator_pulldown = (By.XPATH, '//div[@id="operatorName"]')
    appinst_cloudlet = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Cloudlet"]/sup[text()=" *"]')
    appinst_cloudlet_pulldown = (By.XPATH, '//div[@id="cloudletName"]')
    appinst_cloudlet_pulldown_options = (By.XPATH, '//div[@id="cloudletName"]//div[@role="option"]')
    appinst_flavor = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Flavor"]')
    appinst_flavor_pulldown = (By.XPATH, '//div[@id="flavorName"]')
    appinst_autoclusterinst = (By.XPATH, '//*[@class="four wide column detail_item"]//div[text()="Auto Cluster Instance"]')
    #appinst_autoclusterinst_checkbox = (By.XPATH, '//*[@class="ui fitted toggle checkbox"]')
    appinst_autoclusterinst_checkbox = (By.XPATH, '//div[@class="three column row formRow-8"]//span[@class="MuiIconButton-label"]')
    appinst_ipaccess_pulldown = (By.XPATH, '//div[@id="ipAccess"]')
    appinst_create_button = (By.XPATH, '//form[@class="ui form"]//button//span[text()="Create"]')
    appinst_clusterinst = (By.XPATH, '//*[@class="ui two column grid"]//div[text()="Cluster Instance"]')
    appinst_clusterinst_pulldown = (By.XPATH, '//div[@id="clusterName"]')
    #appinst_clusterinst_pulldown = (By.XPATH, '//*[@class="ui two column grid"]/div[@class="three column row createAppInst7"]/div[@class="eleven wide column"]/div/div[@class="field"]/div[@class="ui fluid multiple selection dropdown"]/i[@class="dropdown icon"]')
    appinst_clusterinst_pulldown1 = (By.XPATH, '//*[@class="ui two column grid"]/div[@class="three column row createAppInst7"]/div[@class="eleven wide column"]//div[@class="field"]/div[@class="ui active visible fluid multiple selection dropdown"]/div[@class="visible menu transition"]')
    configs_kind_input = (By.XPATH, './/div[@class="visible menu transition"]/div//span[text()="envVarsYaml"]')
    configs_button = (By.XPATH, '//div[@class="ui grid"]//h3[text()="Configs"]/button')
    appinst_create_progress_dialog = (By.XPATH, '//div[@class="MuiDialogContent-root"]')
    appinst_create_progress_dialog_text = (By.XPATH, '//div[@class="MuiDialogContent-root"]//p')

class NewPageLocators(object):
    heading = (By.XPATH, '//*[@class="ui modal transition visible active"]/div[text()="Settings"]')
    #region =  (By.XPATH, '//div[text()[1]="Region" and text()[2]=" *"]')
    region =  (By.XPATH, '//div[text()="Region"]/sup[text()=" *"]')
    #region_pulldown = (By.XPATH, '//*[@class="ui modal transition visible active"]//div[@name="Region" and @role="listbox"]/div[text()="Select Region"]')
    #region_pulldown = (By.XPATH, '//*[@class="ui modal transition visible active"]//div[@name="Region" and @role="listbox"]')
    region_pulldown = (By.XPATH, '//div[@id="region"]')
    region_pulldown_option = (By.XPATH, '//div[@role="combobox"]')
    region_pulldown_option_us = (By.XPATH, '//span[text()="US"]')
    region_pulldown_option_eu = (By.XPATH, '//span[text()="EU"]')
    #cancel_button = (By.XPATH, '//*[@class="ui modal transition visible active"]//button[text()="Cancel"]')
    cancel_button = (By.XPATH, '//form[@class="ui form"]//span[text()="Cancel"]/ancestor::button')
    #save_button = (By.XPATH, '//*[@class="ui modal transition visible active"]//button[text()="Save"]')
    save_button = (By.XPATH, '//form[@class="ui form"]//span[text()="Create"]/ancestor::button')

    flavor_heading = (By.XPATH, '//h2[text()="Flavors"]')
    flavor_flavorname = (By.XPATH, '//div[text() ="Flavor Name"]/sup[text() = " *"]')
    flavor_flavorname_input = (By.XPATH, '//input[@placeholder="Enter Flavor Name"]')
    flavor_ram = (By.XPATH, '//div[text() ="RAM Size"]/sup[text() =" *"]')
    flavor_ram_input = (By.XPATH, '//input[@placeholder="Enter RAM Size (MB)"]')
    #flavor_ram_input = (By.NAME, 'vCPUs')
    flavor_vcpus = (By.XPATH, '//div[text() ="Number of vCPUs"]/sup[text() =" *"]')
    flavor_vcpus_input = (By.XPATH, '//input[@placeholder="Enter Number of vCPUs"]')
    #flavor_vcpus_input = (By.NAME, 'vCPUs')
    flavor_disk = (By.XPATH, '//div[text() ="Disk Space"]/sup[text() =" *"]')
    flavor_disk_input = (By.XPATH, '//input[@placeholder="Enter Disk Space (GB)"]')
    #flavor_disk_input = (By.NAME, 'Disk')

    flavor_flavorname_detail = (By.XPATH, '//td[text()="Flavor Name"]')
    flavor_ram_detail = (By.XPATH, '//td[text()="RAM Size(MB)"]')
    flavor_vcpus_detail = (By.XPATH, '//td[text()="Number of vCPUs"]')
    flavor_disk_detail = (By.XPATH, '//td[text()="Disk Space(GB)"]')
    flavor_gpu_detail = (By.XPATH, '//td[text()="GPU"]')
    flavor_gpu_slider = (By.XPATH, '//div[contains(text(),"GPU")]/../../div/following-sibling::div//input')

    cloudlet_heading =  (By.XPATH, '//h2[text()="Create Cloudlet"]')
    #cloudlet_cloudletname = (By.XPATH, '//*[@class="ui form fieldForm"]//div[text()[1]="Cloudlet Name" and text()[2]=" *"]')
    cloudlet_cloudletname = (By.XPATH, '//div[text()="Cloudlet Name"]/sup[text()=" *"]')
    cloudlet_cloudletname_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter cloudlet Name"]')
    cloudlet_operatorname = (By.XPATH, '//div[text()="Operator"]/sup[text()=" *"]')
    #cloudlet_operatorname_input = (By.NAME, 'OperatorName')
    cloudlet_operatorname_input = (By.XPATH, '//div[contains(@class,"default text") and text()="Select Operator"]')
    cloudlet_operator_pulldown = (By.XPATH, '//div[@id="operatorName"]')
    cloudlet_latitude = (By.XPATH, '//label[contains(.,"Latitude") and contains(.,"*")]')
    cloudlet_latitude_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="-90 ~ 90"]')
    cloudlet_longitude = (By.XPATH, '//label[contains(.,"Longitude") and contains(.,"*")]')
    cloudlet_longitude_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="-180 ~ 180"]')
    cloudlet_location = (By.XPATH, '//div[text()="Cloudlet Location"]/sup[text()=" *"]')
    cloudlet_ipsupport = (By.XPATH, '//div[text()="IP Support"]/sup[text()=" *"]')
    cloudlet_ipsupport_input = (By.XPATH, '//div[contains(@class,"default text") and text()="Select IP Support"]')
    cloudlet_ipsupport_pulldown = (By.XPATH, '//div[@id="ipSupport"]')
    #cloudlet_numdynamicips = (By.XPATH, '//*[@class="ui form fieldForm"]//div[text()[1]="Number of Dynamic IPs" and text()[2]=" *"]')
    cloudlet_numdynamicips = (By.XPATH, '//div[text()="Number of Dynamic IPs"]/sup[text()=" *"]')
    #cloudlet_numdynamicips_input = (By.NAME, 'Num_dynamic_ips')
    cloudlet_numdynamicips_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Number of Dynamic IPs"]')
    cloudlet_physicalname = (By.XPATH, '//div[text()="Physical Name"]/sup[text()=" *"]')
    cloudlet_physicalname_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Physical Name"]')
    cloudlet_platformtype = (By.XPATH, '//div[text()="Platform Type"]/sup[text()=" *"]')
    cloudlet_platformtype_input = (By.XPATH, '//div[contains(@class,"default text") and text()="Select Platform Type"]')
    cloudlet_platformtype_pulldown = (By.XPATH, '//div[@id="platformType"]')
    access_mode_input = (By.XPATH, '//div[@id="infraApiAccess"]')
    access_mode_option = (By.XPATH, './/div[@role="listbox"]/div[@role="option"]')
    external_network_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Infra External Network Name"]')
    infra_flavor_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Infra Flavor Name"]')
    get_manifest_header = (By.XPATH, '//h2/b[text()="Cloudlet Manifest"]')
    get_manifest_steps = (By.XPATH, '//h4/b[text()="Perform the following steps to setup cloudlet"]')
    download_manifest_button = (By.XPATH, '//button[@title="download"]')
    close_manifest_button = (By.XPATH, '//div[@style="color: white;"]//button[@class="MuiButtonBase-root MuiIconButton-root" and @type="button"]')
    cloudlet_advancedsettings_button = (By.XPATH, '//div[@class="ui grid"]//h3[text()="Advanced Settings"]/button[@type="button"]')
    trust_policy_pulldown = (By.XPATH, '//div[@id="trustPolicyName"]')
    trust_policy_row = (By.XPATH, '//div[text()="Trust Policy"]')

class NewPageFullLocators(object):
    settings_window = (By.XPATH, '//*[@class="ui grid"]')
    heading = (By.XPATH, '//*[@class="ui header" and text()="Settings"]')
    region =  (By.XPATH, '//div[text()="Region"]/sup[text()=" *"]')

    region_pulldown = (By.XPATH, '//div[@id="region"]')
    region_pulldown_option_us = (By.XPATH, '//*[@class="ui modal transition visible active"]//div[@name="Region" and @role="listbox"]//div[@role="option"]/span[text()="US"]')
    region_pulldown_option_eu = (By.XPATH, '//*[@class="ui modal transition visible active"]//div[@name="Region" and @role="listbox"]//div[@role="option"]/span[text()="EU"]')
    cancel_button = (By.XPATH, '//form[@class="ui form"]//span[text()="Cancel"]/ancestor::button')
    save_button = (By.XPATH, '//*[@role="button" and text()="Save"]')
    create_button = (By.XPATH, '//form[@class="ui form"]//span[text()="Create"]/ancestor::button')

class SignupPageLocators(object):
    title = (By.XPATH, '//span[@class="title" and text()="Create New Account"]')
    username_field = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Username"]')
    password_field = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Password"]')
    confirm_password_field = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Confirm Password"]')
    email_field = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Email ID"]')
    signup_button = (By.XPATH, '//span[text()="Sign Up"]')
    login_switch_button = (By.XPATH, '//button/span[text()="Login"]')
    #signup_switch_button = (By.XPATH, '//button/span[text()="Create an account"]')
    #agree_text = (By.XPATH, '//a[@href="https://www.mobiledgex.com/privacy-policy" and text()="By clicking SignUp, you agree to our Terms, Data Policy, and Cookies Policy."]')

    agree_text = (By.XPATH, '//div[@class="login-text" and contains(text(), "By clicking SignUp, you agree to our")]')
    terms_link = (By.XPATH, '//a[@href="https://mobiledgex.com/terms-of-use" and text()="Terms of Use"]')
    datapolicy_link = (By.XPATH, '//a[@href="https://www.mobiledgex.com/privacy-policy" and text()="Data Policy"]')
    cookiespolicy_link = (By.XPATH, '//a[@href="https://www.mobiledgex.com/privacy-policy" and text()="Cookies Policy"]')
    privacypolicy_link = (By.XPATH, '//a[@href="https://www.mobiledgex.com/privacy-policy" and text()="Trust Policy"]')

class DetailsPageLocators(object):
    details_data = (By.CSS_SELECTOR, 'div.ui.divided.grid')
    #details_row = (By.CSS_SELECTOR, 'div.ui.small.modal.transition.visible.active div.two.column.row')
    #details_row = (By.XPATH, '//table[@class="ui celled table"]/tbody/tr')
    details_row = (By.XPATH, '//table[@class="MuiTable-root"]/tbody/tr')
    #user_details_row = (By.CSS_SELECTOR, 'div.ui.tiny.modal.transition.visible.active div.two.column.row')
    user_details_row = (By.XPATH, '//table[@class="ui celled table"]/tbody/tr')
    #details_row_key = (By.XPATH, './td[1]')
    details_row_key = (By.XPATH, '//tbody[@class="MuiTableBody-root"]/tr/td')
    #details_row_value = (By.XPATH, './td[2]')
    details_row_value = (By.XPATH, '//tbody[@class="MuiTableBody-root"]/tr/td/div')
    #details_title = (By.CSS_SELECTOR, 'div.ui.small.modal.transition.visible.active div.header')
    details_title = (By.CSS_SELECTOR, 'label.content_title_label')
    close_button =  (By.XPATH, '//span[text()="close"]/ancestor::button')
    region_label =  (By.XPATH, '//*[@class="ui small modal transition visible active"]//div[text()="Region"]')

class DetailsFullPageLocators(object):
    #details_data = (By.CSS_SELECTOR, 'div.ui.divided.grid')
    details_row = (By.XPATH, '//table/tbody/tr')
    #details_row_key = (By.XPATH, './td[1]//div')
    details_row_key = (By.XPATH, './td[1]')
    #details_row_value = (By.XPATH, './td[2]')
    details_row_value = (By.XPATH, './td[2]//div')
    details_row_value_updated = (By.XPATH, './td[2]')
    details_title = (By.CSS_SELECTOR, 'div.column.title_align')
    close_button =  (By.XPATH, '//button[text()="Close Details"]')
    subject_heading = (By.XPATH, '//th//div[text()="Subject"]')
    value_heading = (By.XPATH, '//th//div[text()="Value"]')
    region_label =  (By.XPATH, '//td//div[text()="Region"]')

class CloudletDetailsPageLocators(object):
    cloudletname_label = (By.XPATH, '//table/tbody/tr/td[1][text()="Cloudlet"]')
    operator_label = (By.XPATH, '//table/tbody/tr[2]/td[1][text()="Operator"]')
    cloudletlocation_label = (By.XPATH, '//table/tbody/tr[4]/td[1][text()="Cloudlet Location"]')
    ipsupport_label = (By.XPATH, '//table/tbody/tr[5]/td[1][text()="IP Support"]')
    numdynamicips_label = (By.XPATH, '//table/tbody/tr[6]/td[1][text()="Number of Dynamic IPs"]')
    cloudlet_header = (By.XPATH, '//div[@class="MuiToolbar-root MuiToolbar-regular MuiToolbar-gutters"]//h4[text()="Cloudlets"]')
    cloudletname_field = (By.XPATH, '//table/tbody/tr[3]/td[2]/div')

class DeleteConfirmationPageLocators(object):
    no_button = (By.XPATH, '//button/span[text()="NO"]')
    yes_button = (By.XPATH, '//button/span[text()="YES"]')
    header = (By.XPATH, '//button[@class="header"]')
    content = (By.XPATH, '//button[@class="content"]/p[text()="Are you sure you want to delete"]')
    content_item = (By.XPATH, '//button[@class="content"]/p/b')

class OrganizationsPageLocators(object):
    table_header_organization = (By.XPATH, '//label[text()="Organizations"]')
    table_header_type = (By.XPATH, '//table/thead/tr/th/span/div[text()="Type"]')
    table_header_phone = (By.XPATH, '//table/thead/tr/th/span[text()="Phone"]')
    table_header_address = (By.XPATH, '//table/thead/tr/th/span[text()="Address"]')
    table_header_edit = (By.XPATH, '//table/thead/tr/th[text()="Actions"]')

    #add_organization_user = (By.XPATH, './/button[text()="Add User"]')
    add_organization_user = (By.XPATH, '//li[text()="Add User"]')
    table_action = (By.XPATH, '//button[@aria-label="Action"]')
    #add_organization_user_confirm = (By.XPATH, '//button[text()="Add"]')
    add_organization_user_confirm = (By.XPATH, '//span[@class="MuiButton-label" and text()="Add User"]')
    #add_organization_user_finished = (By.XPATH, '//button[text()="Close"]')
    add_organization_user_finished = (By.XPATH, '//span[@class="MuiButton-label" and text()="Skip"]')
    close_button = (By.XPATH, '//span[@class="MuiButton-label" and text()="Close"]')
    return_to_org = (By.XPATH, '//button[text()="Return to Organizations"]')
    #organization_check = (By.XPATH, './/button[@class="ui button"]/i[@class="check icon"]')
    #manage_button = (By.XPATH, './/button[text()="Manage"]')

    #username_input = (By.NAME, 'username')
    username_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Select Username"]')
    role_input = (By.XPATH, '//div[@id="role"]')
    role_pulldown = (By.XPATH, '//*[@class="ui grid popup_user"]//div[@name="selectRole" and @role="listbox"]')
    role_pulldown_option_contributor = (By.XPATH, '//*[@class="ui grid popup_user"]//div[@name="selectRole" and @role="listbox"]//div[@role="option"]/span[text()="Contributor"]')
    role_pulldown_option_manager = (By.XPATH, '//*[@class="ui grid popup_user"]//div[@name="selectRole" and @role="listbox"]//div[@role="option"]/span[text()="Manager"]')
    role_pulldown_option_viewer = (By.XPATH, '//*[@class="ui grid popup_user"]//div[@name="selectRole" and @role="listbox"]//div[@role="option"]/span[text()="Viewer"]')
 
class OrganizationDetailsPageLocators(object):
    organization_label = (By.XPATH, '//table//tr[1]/td[1][text()="Organization"]')
    type_label = (By.XPATH, '//table//tr[2]/td[1][text()="Type"]')
    phone_label = (By.XPATH, '//table//tr[3]/td[1][text()="Phone"]')
    address_label = (By.XPATH, '//table//tr[4]/td[1][text()="Address"]')

    organization_field = (By.XPATH, '//table//tr[1]/td[2]')
    type_field = (By.XPATH, '//table//tr[2]/td[2]')
    phone_field = (By.XPATH, '//table//tr[3]/td[2]')
    address_field = (By.XPATH, '//table//tr[4]/td[2]')

    instructions_text = (By.XPATH, '//*[@class="ui small modal transition visible active"]//div[@class="ui grid"]//div[@class="column"]')
    
class NewOrganizationPageLocators(object):
    cancel_button = (By.XPATH, '//div[@class="inline fields"]//span[text()="Cancel"]')
    create_button = (By.XPATH, '//div[@class="inline fields"]//span[text()="Create"]')

    type_radio = (By.XPATH, '//*[@class="ui form fieldForm"]//div[@class="ui grid"]/div[1]/div[2]')

    #title = (By.XPATH, '//*[@class="content_title" and text()="Create new Organization"]')
    heading = (By.XPATH, '//h2[text()="Create Organization"]')
    step1_active = (By.XPATH, '//*[@class="ui tablet stackable steps"]/div[1][@class="active step"]//div[div[1]="Step 1" and div[2]="Create Organization"]')
    step2_inactive = (By.XPATH, '//*[@class="ui tablet stackable steps"]/div[2][@class="step"]//div[div[1]="Step 2" and div[2]="Add User"]')
    step3_inactive = (By.XPATH, '//*[@class="ui tablet stackable steps"]/div[3][@class="step"]//div[div[1]="Step 3" and div[2]="Review Organization"]')

    #organization_name_label = (By.XPATH, '//*[@class="ui form fieldForm"]/div[3]//div[@class="ui grid"]/div[1]/div[1]/div[text()="Organization Name *"]')
    organization_name_label = (By.XPATH, '//div[text()="Organization Name"]/sup[text()=" *"]')
    #organization_name_input = (By.XPATH, '//*[@class="ui form fieldForm"]/div[3]//div[@class="ui grid"]/div[1]/div[2]//div[@class="ui input"]/input')
    organization_name_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Organization Name"]')
    #address_label = (By.XPATH, '//*[@class="ui form fieldForm"]/div[3]//div[@class="ui grid"]/div[2]/div[1]/div[text()="Address *"]')
    address_label = (By.XPATH, '//div[text()="Address"]/sup[text()=" *"]')
    #address_input = (By.XPATH, '//*[@class="ui form fieldForm"]/div[3]//div[@class="ui grid"]/div[2]/div[2]//div[@class="ui input"]/input')
    address_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Address"]')
    #phone_label = (By.XPATH, '//*[@class="ui form fieldForm"]/div[3]//div[@class="ui grid"]/div[3]/div[1]/div[text()="Phone *"]')
    phone_label = (By.XPATH, '//div[text()="Phone"]/sup[text()=" *"]')
    #phone_input = (By.XPATH, '//*[@class="ui form fieldForm"]/div[3]//div[@class="ui grid"]/div[3]/div[2]//div[@class="ui input"]/input')
    phone_input = (By.XPATH, '//div[@class="ui input"]/input[@placeholder="Enter Phone Number"]')
    type_label =  (By.XPATH, '//div[text()="Type"]/sup[text()=" *"]')
    #type_developer_label = (By.XPATH, '//*[@class="ui form fieldForm"]//div[@class="ui grid"]/div[1]/div[2]//div[@class="ui radio checkbox"]/label[text()="Developer"]')
    type_developer_label = (By.XPATH, '//div[@class="eleven wide column"]/div[@id="type" and @class="ui disabled fluid search selection dropdown"]')
    #type_operator_label = (By.XPATH, '//*[@class="ui form fieldForm"]//div[@class="ui grid"]/div[1]/div[2]//div[@class="ui radio checkbox"]/label[text()="Operator"]')
    type_operator_label = (By.XPATH, '//div[@class="eleven wide column"]/div[@id="type" and @class="ui disabled fluid search selection dropdown"]')

class UsersPageLocators(object):
    #users_table_header_username = (By.XPATH, '//table/thead/tr/th[text()="Username"]')
    users_table_header_username = (By.XPATH, '//div[text()="Username"]')
    #users_table_header_organization = (By.XPATH, '//table/thead/tr/th[text()="Organization"]')
    users_table_header_organization = (By.XPATH, '//div[text()="Organization"]')
    #users_table_header_roletype = (By.XPATH, '//table/thead/tr/th[text()="Role Type"]')
    users_table_header_roletype = (By.XPATH, '//div[text()="Role Type"]')

    user_name_input = (By.XPATH, '//*[@class="user_search"]//div[@class="ui icon input"]//input[@type="text"]')
    user_pulldown_input = (By.XPATH, '//*[@class="user_search"]//div[@role="combobox"]//input[@type="text"]')
    #user_pulldown_option_user = (By.XPATH, '//*[@class="user_search"]//div[@role="combobox"]//div[@role="alert"]/span[text()="Username"]')
    #user_pulldown_option_organization = (By.XPATH, '//*[@class="user_search"]//div[@role="combobox"]//div[@role="listbox"]//div[@role="option"]/span[text()="Organization"]')
    user_details = (By.XPATH, './/i[@class="user circle big icon"]')
    #user_details = (By.CSS_SELECTOR, 'div.left_menu_item i.user.circle.big.icon')

    users_image = (By.XPATH, '//*[@class="ui small bordered centered image"]')
    users_organization = (By.XPATH, '//div[@class="two column row"]//div[@class="five wide column detail_item"]/div[text()="Organization"]')
    users_role_type = (By.XPATH, '//div[@class="two column row"]//div[@class="five wide column detail_item"]/div[text()="Role Type"]')
    #users_name = (By.XPATH, '//div[@class="row"]//div[@class="column"]/div[text()="XXX"]')
    close_button = (By.XPATH, '//button[@class="ui button" and text()="Close"]')

class AccountsPageLocators(object):
    accounts_table_header_username = (By.XPATH, '//table/thead/tr/th/span[text()="Username"]')
    accounts_table_header_email = (By.XPATH, '//table/thead/tr/th/span[text()="Email"]')
    accounts_table_header_emailverified = (By.XPATH, '//table/thead/tr/th/span[text()="Email Verified"]')
    accounts_table_header_locked = (By.XPATH, '//table/thead/tr/th/span[text()="Locked"]')

    #account_details = (By.XPATH, '//*[@class="user circle big icon"]')
    account_details = (By.XPATH, './/i[@class="user circle big icon"]')
    accounts_details_table = (By.XPATH, '//div[@class="image scrolling content"]')

    accounts_details_username = (By.XPATH, '//td[text()="Username"]')
    accounts_details_email = (By.XPATH, '//td[text()="Email"]')
    accounts_details_email_verification = (By.XPATH, '//td[text()="Email Verified"]')
    #accounts_details_passhash = (By.XPATH, '//div[@class="two column row"]//div[@class="five wide column detail_item"]/div[text()="Passhas"]')
    #accounts_details_salt = (By.XPATH, '//div[@class="two column row"]//div[@class="five wide column detail_item"]/div[text()="Salt"]')
    #accounts_details_iter = (By.XPATH, '//div[@class="two column row"]//div[@class="five wide column detail_item"]/div[text()="Iter"]')
    #accounts_details_family_name = (By.XPATH, '//div[@class="two column row"]//div[@class="five wide column detail_item"]/div[text()="Family Name"]')
    #accounts_details_given_name = (By.XPATH, '//div[@class="two column row"]//div[@class="five wide column detail_item"]/div[text()="GivenName"]')
    #accounts_details_picture = (By.XPATH, '//div[@class="two column row"]//div[@class="five wide column detail_item"]/div[text()="Picture"]')
    #accounts_details_nickname = (By.XPATH, '//div[@class="two column row"]//div[@class="five wide column detail_item"]/div[text()="Nickname"]')
    accounts_details_created_at = (By.XPATH, '//td[text()="Created At"]')
    accounts_details_updated_at = (By.XPATH, '//td[text()="Updated At"]')
    accounts_details_locked = (By.XPATH, '//td[text()="Locked"]')
    close_button = (By.XPATH, '//button[@class="ui button" and text()="Close"]')
    next_page_button = (By.XPATH, '//div[@class="MuiTablePagination-actions"]/button[@type="button" and @title="Next page"]')
