apiVersion: v1
kind: Service
metadata:
  labels:
    app: dme
  name: dme
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
   - name: api
     port: 50051
     protocol: TCP
     targetPort: 50051
   - name: http
     port: 38001
     protocol: TCP
     targetPort: 38001
  selector:
    app: dme
  sessionAffinity: None
  type: LoadBalancer

