# Copyright 2022 MobiledgeX, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
  labels:
    app: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
       hostAliases:
        - ip: "35.202.131.16"
          hostnames:
          - "automation.ctrl.mobiledgex.net"
        - ip: "35.238.36.211"
          hostnames:
          - "automationeu.ctrl.mobiledgex.net"
        - ip: "40.122.108.233"
          hostnames:
          - "automationjaeger.mobiledgex.net"
       containers:
       - name: mc
         image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 10m
         command:
          - mc
         args:
          - "--sqlAddr"
          - "40.122.108.233:5432"
          - "--addr"
          - "0.0.0.0:9900"
          - "--vaultAddr"
          - "https://vault-qa.mobiledgex.net:8200"
          - "-ldapAddr"
          - "0.0.0.0:9389"
          - "--tls"
          - "/root/tls/mex-server.crt"
          - "--tlskey"
          - "/root/tls/mex-server.key"
          - "--clientCert"
          - "/root/tls/mex-server.crt"
          - "-d"
          - "etcd,api,notify"
          - "--gitlabAddr"
          - "https://gitlab-qa.mobiledgex.net"
          - "--artifactoryAddr"
          - "https://artifactory-qa.mobiledgex.net"
          - "--jaegerAddr"
          - "jaeger-qa.mobiledgex.net:16686"
         env:
          - name: VAULT_ROLE_ID
            value: fe150a80-ab52-322a-3b47-771c0e27b9fb 
          - name: VAULT_SECRET_ID
            value: 556c878d-e617-f3c4-e04d-52aa1ed3fd08 
          - name: gitlab_token
            value: gitlabtesttoken
          - name: artifactory_apikey
            value: AKCp5dKiKvWomuRq5h4LiSb5CZAUeoYh5w3Nw1K4irdKFEa41n4h4mYmBax6i83ydMjinJtHu 
          - name: JAEGER_ENDPOINT
            value: https://jaeger-qa.mobiledgex.net:14268/api/traces
       imagePullSecrets:
        - name: mexreg-secret
