apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app: controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
       hostAliases:
       - ip: "40.122.108.233"
         hostnames:
         - "automationjaeger.mobiledgex.net"
       containers:
       - name: controller
         image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 10m
         command:
          - controller
         args:
          - "--etcdUrls"
          - "mex-etcd-cluster:2379"
          - "--notifyAddr"
          - "0.0.0.0:37001"
          - "--apiAddr"
          - "0.0.0.0:55001"
          - "--httpAddr"
          - "0.0.0.0:36001"
          - "--publicAddr"
          - "automation.ctrl.mobiledgex.net"
          - "--region"
          - "US"
          - "--vaultAddr"
          - "https://vault-qa.mobiledgex.net:8200"
          - "--registryFQDN"
          - "docker-qa.mobiledgex.net"
          - "--artifactoryFQDN"
          - "https://artifactory-qa.mobiledgex.net/artifactory"
          - "--cloudletRegistryPath"
          - "registry.mobiledgex.net:5000/mobiledgex/edge-cloud"
          - "--cloudletVMImagePath"
          - "https://artifactory-qa.mobiledgex.net/artifactory/baseimages/mobiledgex-v3.0.0.qcow2#md5:ebf04bdaef81b70a84a4d787730aab3e"
          - "--versionTag"
          - "$AUTOMATION_DOCKERTAG"
          - "--tls"
          - "/root/tls/mex-server.crt"
          - "--influxAddr"
          - "http://35.202.161.23:8086"
          - "-d"
          - "etcd,api,notify,mexos"
          - "-autoUpgrade"
         env:
          - name: VAULT_ROLE_ID
            value: ca6bdaf0-b4c6-98d9-e0bd-b47073541657
          - name: VAULT_SECRET_ID
            value: db9c1b53-b77b-fc48-cc4b-bdabc65b921e
          - name: VAULT_CRM_ROLE_ID
            value: ca425b55-53a4-6fcd-fc27-9f0bd1ee2e92
          - name: VAULT_CRM_SECRET_ID
            value: 52baef16-b4ea-7b85-aca8-df3fa5eb9d41
          - name: JAEGER_ENDPOINT
            value: https://jaeger-qa.mobiledgex.net:14268/api/traces
       imagePullSecrets:
        - name: mexreg-secret
