apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmazurecentral
  labels:
    app: crmazurecentral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmazurecentral
  template:
    metadata:
      labels:
        app: crmazurecentral
    spec:
      containers:
      - name: crmazurecentral
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        env:
         - name: PATH
           value: /tmp/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
         - name: MEXENV_URL
           value: https://vault-qa.mobiledgex.net/v1/secret/data/cloudlet/openstack/mexenv.json
         - name: CLOUDLET_KIND
           value: azure
         - name: MEX_AZURE_LOCATION
           value: centralus
         - name: VAULT_ROLE_ID
           value: ca425b55-53a4-6fcd-fc27-9f0bd1ee2e92 
         - name: VAULT_SECRET_ID
           value: 52baef16-b4ea-7b85-aca8-df3fa5eb9d41 
        args:
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"azure\"},\"name\":\"automationAzureCentralCloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--platform"
         - "PLATFORM_TYPE_AZURE"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--vaultAddr"
         - "https://vault-qa.mobiledgex.net:8200"
         - "--physicalName"
         - "azure"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret
