apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmattcloud1
  labels:
    app: crmattcloud1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmattcloud1
  template:
    metadata:
      labels:
        app: crmattcloud1
    spec:
      containers:
      - name: crmattcloud1
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        args:
         - "--apiAddr"
         - "0.0.0.0:50101"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"att\"},\"name\":\"attcloud-1\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--fakecloudlet"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret
