apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmhamburg
  labels:
    app: crmhamburg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmhamburg
  template:
    metadata:
      labels:
        app: crmhamburg
    spec:
      containers:
      - name: crmhamburg
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        env:
         - name: CLOUDLET_KIND
           value: openstack
         - name: MEX_EXT_NETWORK
           value: external-network-shared
         - name: MEXENV_URL
           value: https://vault-qa.mobiledgex.net/v1/secret/data/cloudlet/openstack/mexenv.json
         - name: VAULT_ROLE_ID
           value: ca425b55-53a4-6fcd-fc27-9f0bd1ee2e92
         - name: VAULT_SECRET_ID
           value: 52baef16-b4ea-7b85-aca8-df3fa5eb9d41
         #- name: CLEANUP_ON_FAILURE
         #  value: "no"
        args:
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"TDG\"},\"name\":\"automationHamburgCloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--platform"
         - "PLATFORM_TYPE_OPENSTACK"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--vaultAddr"
         - "https://vault-qa.mobiledgex.net:8200"
         - "--physicalName"
         - "hamburg"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret

