apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app: controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
       containers:
       - name: controller
         image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 10m
         command:
          - controller
         args:
          - "--etcdUrls"
          - "mex-etcd-cluster:2379"
          - "--notifyAddr"
          - "0.0.0.0:37001"
          - "--apiAddr"
          - "0.0.0.0:55001"
          - "--httpAddr"
          - "0.0.0.0:36001"
          - "--vaultAddr"
          - "https://vault.mobiledgex.net"
          - "--tls"
          - "/root/tls/mex-server.crt"
          - "--influxAddr"
          - "http://35.247.126.154:8086"
          - "-d"
          - "etcd,api,notify"
          - "-autoUpgrade"
         env:
          - name: VAULT_ROLE_ID
            value: 0d0ab025-509e-c37d-d5de-c3319f452bd8
          - name: VAULT_SECRET_ID
            value: 4789ef81-4037-99a2-e966-b0998e677972
       imagePullSecrets:
        - name: mexreg-secret
