apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmtmocloud2eu
  labels:
    app: crmtmocloud2eu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmtmocloud2eu
  template:
    metadata:
      labels:
        app: crmtmocloud2eu
    spec:
      containers:
      - name: crmtmocloud2eu
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        args:
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"tmus\"},\"name\":\"tmocloudeu-2\"}"
         - "--notifyAddrs"
         - "automationeu.ctrl.mobiledgex.net:37002"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--platform"
         - "PLATFORM_TYPE_FAKE"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret

