apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmbonn
  labels:
    app: crmbonn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmbonn
  template:
    metadata:
      labels:
        app: crmbonn
    spec:
      hostAliases:
       - ip: "37.50.143.121"
         hostnames:
         - "bonnedgecloud.telekom.de"
      containers:
      - name: crmbonn
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        args:
         - "--apiAddr"
         - "0.0.0.0:50051"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"TDG\"},\"name\":\"automationBonnCloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret

