apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app: controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
       containers:
       - name: controller
         image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 10m
         command:
          - controller
         args:
          - "--etcdUrls"
          - "mex-etcd-cluster:2379"
          - "--notifyAddr"
          - "0.0.0.0:37001"
          - "--apiAddr"
          - "0.0.0.0:55001"
          - "--httpAddr"
          - "0.0.0.0:36001"
          - "--region"
          - "US"
          - "--vaultAddr"
          - "https://vault-qa.mobiledgex.net:8200"
          - "--registryFQDN"
          - "docker-qa.mobiledgex.net"
          - "--versionTag"
          - "$AUTOMATION_DOCKERTAG"
          - "--tls"
          - "/root/tls/mex-server.crt"
          - "--influxAddr"
          - "http://35.202.161.23:8086"
          - "-d"
          - "etcd,api,notify"
          - "-autoUpgrade"
         env:
          - name: VAULT_ROLE_ID
            value: ca6bdaf0-b4c6-98d9-e0bd-b47073541657
          - name: VAULT_SECRET_ID
            value: db9c1b53-b77b-fc48-cc4b-bdabc65b921e
       imagePullSecrets:
        - name: mexreg-secret
