apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
  labels:
    app: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
       hostAliases:
        - ip: "35.202.131.16"
          hostnames:
          - "automation.ctrl.mobiledgex.net"
        - ip: "35.238.36.211"
          hostnames:
          - "automationeu.ctrl.mobiledgex.net"
       containers:
       - name: mc
         image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 10m
         command:
          - mc
         args:
          - "--sqlAddr"
          - "40.122.108.233:5432"
          - "--addr"
          - "0.0.0.0:9900"
          - "--vaultAddr"
          - "https://vault.mobiledgex.net"
          - "--tls"
          - "/root/tls/mex-server.crt"
          - "--tlskey"
          - "/root/tls/mex-server.key"
          - "--clientCert"
          - "/root/tls/mex-server.crt"
          - "-d"
          - "etcd,api,notify"
          - "--gitlabAddr"
          - "https://gitlab-qa.mobiledgex.net"
          - "--artifactoryAddr"
          - "https://artifactory.mobiledgex.net"
          - "--tag"
          - "qa"
         env:
          - name: VAULT_ROLE_ID
            value: f4207f0f-c965-ac3e-181c-235de8838ff7
          - name: VAULT_SECRET_ID
            value: 528a3921-5afc-0150-1f9b-9e1fa4a49727
          - name: gitlab_token
            value: gitlabtesttoken
          - name: artifactory_apikey
            value: ***REMOVED***
       imagePullSecrets:
        - name: mexreg-secret
