apiVersion: apps/v1
kind: Deployment
metadata:
  name: controllereu
  labels:
    app: controllereu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controllereu
  template:
    metadata:
      labels:
        app: controllereu
    spec:
       hostAliases:
       - ip: "40.122.108.233"
         hostnames:
         - "automationjaeger.mobiledgex.net"
       containers:
       - name: controllereu
         image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 10m
         command:
          - controller
         args:
          - "--etcdUrls"
          - "mex-etcd-cluster-eu:2379"
          - "--notifyAddr"
          - "0.0.0.0:37002"
          - "--apiAddr"
          - "0.0.0.0:55002"
          - "--httpAddr"
          - "0.0.0.0:36002"
          - "--region"
          - "EU"
          - "--vaultAddr"
          - "https://vault-qa.mobiledgex.net:8200"
          - "--registryFQDN"
          - "docker-qa.mobiledgex.net"
          - "--artifactoryFQDN"
          - "https://artifactory-qa.mobiledgex.net/artifactory"
          - "--cloudletRegistryPath"
          - "registry.mobiledgex.net:5000/mobiledgex/edge-cloud"
          - "--cloudletVMImagePath"
          - "https://artifactory-qa.mobiledgex.net/artifactory/baseimages/mobiledgex-v3.0.0.qcow2#md5:ebf04bdaef81b70a84a4d787730aab3e"
          - "--versionTag"
          - "$AUTOMATION_DOCKERTAG"
          - "--tls"
          - "/root/tls/mex-server.crt"
          - "--influxAddr"
          - "http://35.202.161.23:8086"
          - "-d"
          - "etcd,api,notify,mexos"
          - "-autoUpgrade"
         env:
          - name: VAULT_ROLE_ID
            value: 18a54dd0-b89b-17dd-3fa4-83dfc2ef3d9c
          - name: VAULT_SECRET_ID
            value: f53d7e38-9568-be39-7d03-9ad3eb973d29
          - name: VAULT_CRM_ROLE_ID
            value: ca425b55-53a4-6fcd-fc27-9f0bd1ee2e92
          - name: VAULT_CRM_SECRET_ID
            value: ***REMOVED***
          - name: JAEGER_ENDPOINT
            value: https://jaeger-qa.mobiledgex.net:14268/api/traces
       imagePullSecrets:
        - name: mexreg-secret
