# Copyright 2022 MobiledgeX, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmtmocloud1-v100
  labels:
    app: crmtmocloud1-v100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmtmocloud1-v100
  template:
    metadata:
      labels:
        app: crmtmocloud1-v100
    spec:
      containers:
      - name: crmtmocloud1-v100
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:v1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        args:
         - "--apiAddr"
         - "0.0.0.0:50091"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"dmuus\"},\"name\":\"tmocloud-1\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--fakecloudlet"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret
