apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmazurecentral-v100
  labels:
    app: crmazurecentral-v100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmazurecentral-v100
  template:
    metadata:
      labels:
        app: crmazurecentral-v100
    spec:
      containers:
      - name: crmazurecentral-v100
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:v1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        env:
         - name: PATH
           value: /tmp/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
         - name: MEXENV_URL
           value: https://vault.mobiledgex.net/v1/secret/data/cloudlet/openstack/mexenv.json
         - name: CLOUDLET_KIND
           value: azure
         - name: MEX_AZURE_LOCATION
           value: centralus
        args:
         - "--apiAddr"
         - "0.0.0.0:65100"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"azure\"},\"name\":\"automationProdAzureCentralCloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret
