apiVersion: v1
kind: Service
metadata:
  labels:
    app: dme-v100
  name: dme-v100
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
   - port: 50051
     protocol: TCP
     targetPort: 50051
  selector:
    app: dme-v100
  sessionAffinity: None
  type: LoadBalancer

