apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-v100
  labels:
    app: controller-v100
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
       containers:
       - name: controller
         image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:v1.0.0
         imagePullPolicy: Always
         resources:
           requests:
             cpu: 10m
         command:
          - controller
         args:
          - "--etcdUrls"
          - "mex-etcd-cluster:2379"
          - "--notifyAddr"
          - "0.0.0.0:37001"
          - "--apiAddr"
          - "0.0.0.0:55001"
          - "--httpAddr"
          - "0.0.0.0:36001"
          - "--tls"
          - "/root/tls/mex-server.crt"
          - "-d"
          - "etcd,api,notify"
       imagePullSecrets:
        - name: mexreg-secret

