# Copyright 2022 MobiledgeX, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmhamburg-v100
  labels:
    app: crmhamburg-v100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmhamburg-v100
  template:
    metadata:
      labels:
        app: crmhamburg-v100
    spec:
      containers:
      - name: crmhamburg-v100
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:v1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        env:
         - name: CLOUDLET_KIND
           value: openstack
         - name: MEX_OS_IMAGE
           value: mobiledgex
         - name: MEX_EXT_NETWORK
           value: external-network-shared
         - name: OPENRC_URL
           value: https://vault.mobiledgex.net/v1/secret/data/cloudlet/openstack/hamburg/openrc.json
         - name: MEXENV_URL
           value: https://vault.mobiledgex.net/v1/secret/data/cloudlet/openstack/mexenv.json
        args:
         - "--apiAddr"
         - "0.0.0.0:50054"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"TDG\"},\"name\":\"automationProdHamburgCloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret

