apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server-ping-threaded-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "server-ping-threaded-chart.name" . }}
    helm.sh/chart: {{ include "server-ping-threaded-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "server-ping-threaded-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "server-ping-threaded-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.repository }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp{{ .Values.service.tcpport }}
              containerPort: {{ .Values.service.tcpport }}
              protocol: TCP
            - name: udp{{ .Values.service.udpport }}
              containerPort: {{ .Values.service.udpport }}
              protocol: UDP	      
          command:
            -  "{{ .Values.image.command }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
